"""Projection rewrites — collapse stacked projections and prune unread columns.

Chained `select` / `with_columns` / `rename` / `drop` build a stack of `Project`
nodes, each a full pass over the batch. `merge_projections` folds two adjacent
projections into one by substituting the inner projection's expressions into the
outer's — `Project(Project(x))` becomes a single `Project(x)` computing the same
columns. It guards against inlining a computation more than once, so the merge
never increases work: it removes an operator (and drops any unused inner column),
or it does nothing.

`rewrite_projection` (the whole-plan `projection_rewrite` rule) prunes columns the
plan never uses. It walks top-down tracking the *required* column set, narrowing it
at each operator, and rewrites `Join` nodes to drop output columns no downstream
operator consumes. `required_columns_per_source` is the companion analysis that
arrives at each `Scan` with exactly the columns it must produce (the source's read
projection) — consumed by the optimizer to build `PhysicalPlan.source_projections`.
"""

from __future__ import annotations

from batcher.kyber.pass_base import OptimizerContext
from batcher.kyber.registry import rule
from batcher.kyber.rule import Phase
from batcher.plan.expr_ir import Col, Expr, referenced_columns
from batcher.plan.expr_rewrite import substitute_columns as _substitute_cols
from batcher.plan.expr_rewrite import transform_expr_up
from batcher.plan.logical import (
    Aggregate,
    AsofJoin,
    Distinct,
    Filter,
    Join,
    Limit,
    LogicalPlan,
    Project,
    Projection,
    Sample,
    Scan,
    Sort,
    Union,
    Unnest,
    Unpivot,
    Window,
)

__all__ = [
    "eliminate_identity_project",
    "merge_projections",
    "push_filter_through_project",
    "required_columns_per_source",
    "required_predicates_per_source",
    "rewrite_projection",
]


def _col_ref_counts(exprs: list[Expr]) -> dict[str, int]:
    """How many times each column name is referenced across `exprs` (occurrences,
    not distinct), so we can refuse a merge that would duplicate a computation."""
    counts: dict[str, int] = {}

    def tally(e: Expr) -> Expr:
        if isinstance(e, Col):
            counts[e.name] = counts.get(e.name, 0) + 1
        return e

    for ex in exprs:
        transform_expr_up(ex, tally)
    return counts


@rule(name="eliminate_identity_project", phase=Phase.NORMALIZE, matches=(Project,))
def eliminate_identity_project(node: Project, _ctx: OptimizerContext) -> LogicalPlan | None:
    """`Project(x)` → `x` when the projection outputs exactly `x`'s columns, in
    order, unchanged (every item is `Col(c)` aliased to `c`). Such no-op projections
    are commonly generated by `select`-all, column pruning, or other rewrites;
    removing them drops a whole pass over the batch."""
    input_cols = node.input.available_columns()
    if len(node.items) != len(input_cols):
        return None
    for item, col_name in zip(node.items, input_cols, strict=True):
        is_passthrough = isinstance(item.expr, Col) and item.expr.name == col_name
        if item.alias != col_name or not is_passthrough:
            return None
    return node.input


@rule(name="merge_projections", phase=Phase.NORMALIZE, matches=(Project,))
def merge_projections(node: Project, _ctx: OptimizerContext) -> LogicalPlan | None:
    """`Project(Project(x))` → one `Project(x)` by inlining the inner expressions.

    The outer projection's expressions reference the inner projection's output
    columns; substituting each inner column with its defining expression yields
    equivalent expressions over the inner *input*, so the two passes collapse to
    one with an identical result and schema.

    Guarded to never duplicate work: if any inner output column is referenced more
    than once by the outer projection, inlining it would compute it repeatedly, so
    the merge is skipped. (Inner columns referenced zero times simply vanish —
    dead-column elimination.)
    """
    inner = node.input
    if not isinstance(inner, Project):
        return None
    counts = _col_ref_counts([it.expr for it in node.items])
    if any(counts.get(it.alias, 0) > 1 for it in inner.items):
        return None
    inner_map = {it.alias: it.expr for it in inner.items}
    new_items = tuple(
        Projection(it.alias, _substitute_cols(it.expr, inner_map)) for it in node.items
    )
    return Project(inner.input, new_items)


@rule(name="push_filter_through_project", phase=Phase.PUSHDOWN, matches=(Filter,))
def push_filter_through_project(node: Filter, _ctx: OptimizerContext) -> LogicalPlan | None:
    """`Filter(Project(x), p)` → `Project(Filter(x, p'), items)` when `p` references
    only pass-through (rename) columns of the projection.

    Pushing the filter below the projection evaluates it earlier (and lets it reach
    a join/scan underneath). It is only safe for predicates over *pass-through*
    columns — aliases whose projection expression is a bare `Col`. If the predicate
    depended on a *computed* column, pushing the filter under the projection would
    reorder that computation relative to the filter and could change null/error
    behaviour (e.g. a row the filter would drop might now never hit a division that
    errors). Restricting to renames makes `p'` a pure column-renaming of `p`, so no
    computation moves across the filter and the result is identical.
    """
    inner = node.input
    if not isinstance(inner, Project):
        return None
    passthrough = {it.alias: it.expr for it in inner.items if isinstance(it.expr, Col)}
    if not referenced_columns(node.predicate) <= set(passthrough):
        return None
    new_pred = _substitute_cols(node.predicate, passthrough)
    return Project(Filter(inner.input, new_pred), inner.items)


def _window_child_need(node: Window, need: set[str]) -> set[str]:
    """Columns a Window's child must produce: the downstream-needed *input*
    columns plus every column the partition/order keys and function inputs read.
    (Function-output aliases come from the Window itself, not the child.)"""
    input_cols = set(node.input.available_columns())
    child_need = set(need) & input_cols
    for expr in node.partition_keys:
        child_need |= referenced_columns(expr)
    for key in node.order_keys:
        child_need |= referenced_columns(key.expr)
    for fn in node.functions:
        if fn.input is not None:
            child_need |= referenced_columns(fn.input)
    return child_need


def _unnest_child_need(node: Unnest, need: set[str]) -> set[str]:
    """Columns an Unnest's child must produce: the exploded list `column` always
    (it determines the output row count, even when its values aren't read), plus
    every downstream-needed pass-through column. The `alias` output maps back to
    `column` on the child."""
    child_need = {node.column}
    for n in need:
        child_need.add(node.column if n == node.alias else n)
    return child_need


def rewrite_projection(plan: LogicalPlan) -> LogicalPlan:
    """Prune columns the plan never uses.

    Currently this rewrites `Join` nodes to drop output columns no downstream
    operator consumes (a join materializes a fixed output list, so unused columns
    must be removed from the plan, not merely left unread). Other nodes only
    reference the columns they use, so pruning their sources via
    `required_columns_per_source` suffices.
    """
    return _rewrite(plan, set(plan.available_columns()))


def _rewrite(node: LogicalPlan, need: set[str]) -> LogicalPlan:
    if isinstance(node, Scan):
        return node
    if isinstance(node, Filter):
        child = _rewrite(node.input, need | referenced_columns(node.predicate))
        return Filter(child, node.predicate)
    if isinstance(node, Project):
        # Drop output columns nothing downstream consumes (keep ≥1), then prune
        # the scan to only what the surviving expressions read.
        kept = tuple(item for item in node.items if item.alias in need)
        if not kept:
            kept = node.items[:1]
        child_need: set[str] = set()
        for item in kept:
            child_need |= referenced_columns(item.expr)
        return Project(_rewrite(node.input, child_need), kept)
    if isinstance(node, Aggregate):
        child_need = set()
        for key in node.group_keys:
            child_need |= referenced_columns(key.expr)
        for spec in node.aggregates:
            if spec.agg.input is not None:
                child_need |= referenced_columns(spec.agg.input)
            # arg_min/arg_max also reference an ordering key (the second input).
            if spec.agg.input2 is not None:
                child_need |= referenced_columns(spec.agg.input2)
        return Aggregate(_rewrite(node.input, child_need), node.group_keys, node.aggregates)
    if isinstance(node, Sort):
        child_need = set(need)
        for key in node.keys:
            child_need |= referenced_columns(key.expr)
        return Sort(_rewrite(node.input, child_need), node.keys, node.limit)
    if isinstance(node, Window):
        child_need = _window_child_need(node, need)
        return Window(
            _rewrite(node.input, child_need),
            node.partition_keys,
            node.order_keys,
            node.functions,
            node.rank_limit,
        )
    if isinstance(node, Unnest):
        # The exploded `column` is always needed (it sets the row count); other
        # downstream needs pass through, with `alias` mapping back to `column`.
        return Unnest(_rewrite(node.input, _unnest_child_need(node, need)), node.column, node.alias)
    if isinstance(node, Unpivot):
        # Unpivot's child must produce the index + melted `on` columns; the output's
        # variable/value columns are synthesized here, not read from the child.
        child_need = set(node.index) | set(node.on)
        return Unpivot(
            _rewrite(node.input, child_need),
            node.index,
            node.on,
            node.variable_name,
            node.value_name,
        )
    if isinstance(node, Sample):
        # Sample preserves the schema; its child needs exactly what's needed above.
        return Sample(_rewrite(node.input, set(need)), node.fraction, node.seed, node.n)
    if isinstance(node, Limit):
        return Limit(_rewrite(node.input, set(need)), node.n, node.offset)
    if isinstance(node, Distinct):
        # Distinct uses every column, so its child needs them all.
        return Distinct(_rewrite(node.input, set(node.input.available_columns())))
    if isinstance(node, Union):
        return Union(
            tuple(_rewrite(i, set(i.available_columns())) for i in node.inputs),
            node.distinct,
        )
    if isinstance(node, Join):
        # Always retain the key output columns (named after the left keys) so the
        # join keeps ≥1 column and the keys stay available.
        key_aliases = set(node.left_keys)
        new_output = tuple(
            spec for spec in node.output if spec.alias in need or spec.alias in key_aliases
        )
        left_need = set(node.left_keys) | {s.name for s in new_output if s.side == "left"}
        right_need = set(node.right_keys) | {s.name for s in new_output if s.side == "right"}
        return Join(
            _rewrite(node.left, left_need),
            _rewrite(node.right, right_need),
            node.left_keys,
            node.right_keys,
            node.join_type,
            new_output,
        )
    if isinstance(node, AsofJoin):
        # Each child needs its match keys (`on` + `by`) plus the output columns drawn
        # from that side; the output spec itself is left intact.
        left_need = {
            node.left_on,
            *node.left_by,
            *(s.name for s in node.output if s.side == "left"),
        }
        right_need = {
            node.right_on,
            *node.right_by,
            *(s.name for s in node.output if s.side == "right"),
        }
        return AsofJoin(
            _rewrite(node.left, left_need),
            _rewrite(node.right, right_need),
            node.left_on,
            node.right_on,
            node.left_by,
            node.right_by,
            node.direction,
            node.output,
        )
    raise TypeError(f"projection rewrite: unhandled node {type(node).__name__}")


def required_columns_per_source(plan: LogicalPlan) -> dict[int, list[str]]:
    """Return, per scan `source_id`, the column projection to read.

    A scan with an empty requirement still reads one column so row counts are
    preserved (e.g. ``count(*)`` needs rows but no values).
    """
    required: dict[int, set[str]] = {}
    _visit(plan, set(plan.available_columns()), required)

    out: dict[int, list[str]] = {}
    for source_id, cols in required.items():
        # Preserve a stable, schema-ordered projection.
        out[source_id] = sorted(cols)
    return out


def required_predicates_per_source(plan: LogicalPlan) -> dict[int, dict]:
    """Return, per scan `source_id`, the predicate IR of a `Filter` directly above it.

    After predicate-pushdown rules run, a residual `Filter` typically sits just
    above each `Scan`; its predicate is the candidate for source-side pushdown. A
    pushdown-capable source translates the pushable subset; the engine keeps the
    `Filter`, so recording the predicate here never changes results — at worst the
    source ignores it. Filters separated from the scan by other operators are not
    pushed (conservative), and multiple stacked filters over one scan are AND-combined.
    """
    acc: dict[int, dict] = {}
    _collect_scan_predicates(plan, None, acc)
    return acc


def _collect_scan_predicates(node: LogicalPlan, pending: Expr | None, acc: dict[int, dict]) -> None:
    """Walk down carrying the predicate of an immediately-enclosing `Filter`."""
    if isinstance(node, Scan):
        if pending is not None:
            acc[node.source_id] = pending.to_ir()
        return
    if isinstance(node, Filter):
        combined = node.predicate if pending is None else _and(pending, node.predicate)
        _collect_scan_predicates(node.input, combined, acc)
        return
    # Any other operator breaks the Filter→Scan adjacency: descend with no pending
    # predicate (children get their own immediately-enclosing filters, if any).
    for child in _children(node):
        _collect_scan_predicates(child, None, acc)


def _and(left: Expr, right: Expr) -> Expr:
    from batcher.plan.expr_ir import Binary

    return Binary("and", left, right)


def _children(node: LogicalPlan) -> tuple[LogicalPlan, ...]:
    if isinstance(node, (Join, AsofJoin)):
        return (node.left, node.right)
    if isinstance(node, Union):
        return tuple(node.inputs)
    inp = getattr(node, "input", None)
    return (inp,) if inp is not None else ()


def _visit(node: LogicalPlan, need: set[str], acc: dict[int, set[str]]) -> None:
    if isinstance(node, Scan):
        available = node.schema.names
        keep = [c for c in available if c in need]
        if not keep:
            # Read one column to preserve cardinality (count(*), etc.).
            keep = [available[0]]
        acc.setdefault(node.source_id, set()).update(keep)

    elif isinstance(node, Filter):
        _visit(node.input, need | referenced_columns(node.predicate), acc)

    elif isinstance(node, Project):
        child_need: set[str] = set()
        for item in node.items:
            if item.alias in need:
                child_need |= referenced_columns(item.expr)
        _visit(node.input, child_need, acc)

    elif isinstance(node, Aggregate):
        child_need = set()
        for key in node.group_keys:
            child_need |= referenced_columns(key.expr)
        for spec in node.aggregates:
            if spec.agg.input is not None:
                child_need |= referenced_columns(spec.agg.input)
            if spec.agg.input2 is not None:
                child_need |= referenced_columns(spec.agg.input2)
        _visit(node.input, child_need, acc)

    elif isinstance(node, Sort):
        child_need = set(need)
        for key in node.keys:
            child_need |= referenced_columns(key.expr)
        _visit(node.input, child_need, acc)

    elif isinstance(node, Window):
        _visit(node.input, _window_child_need(node, need), acc)

    elif isinstance(node, Limit):
        _visit(node.input, set(need), acc)

    elif isinstance(node, Distinct):
        _visit(node.input, set(node.input.available_columns()), acc)

    elif isinstance(node, Union):
        for inp in node.inputs:
            _visit(inp, set(inp.available_columns()), acc)

    elif isinstance(node, Join):
        left_need = set(node.left_keys)
        right_need = set(node.right_keys)
        for col in node.output:
            if col.alias in need:
                if col.side == "left":
                    left_need.add(col.name)
                else:
                    right_need.add(col.name)
        _visit(node.left, left_need, acc)
        _visit(node.right, right_need, acc)

    elif isinstance(node, AsofJoin):
        left_need = {node.left_on, *node.left_by}
        right_need = {node.right_on, *node.right_by}
        for col in node.output:
            if col.alias in need:
                (left_need if col.side == "left" else right_need).add(col.name)
        _visit(node.left, left_need, acc)
        _visit(node.right, right_need, acc)

    elif isinstance(node, Unnest):
        _visit(node.input, _unnest_child_need(node, need), acc)

    elif isinstance(node, Unpivot):
        _visit(node.input, set(node.index) | set(node.on), acc)

    elif isinstance(node, Sample):
        _visit(node.input, set(need), acc)

    else:  # pragma: no cover - defensive
        raise TypeError(f"projection pushdown: unhandled node {type(node).__name__}")
