"""The geospatial function family: PostGIS-named `ST_*` functions over WKB geometry.

A geometry column is WKB in an Arrow `Binary` column, which is what GeoParquet, PostGIS
and DuckDB spatial all store, so a column round-trips through any of them unconverted.
Every function here is a thin wrapper that lowers to one `GeoFunc` IR node; the geometry
model, codecs and planar algorithms live in the `bc-geo` Rust crate.

Grouped by module: `codecs` reads and writes the text encodings, `construct` builds
geometries and derives simpler shapes, `accessors` and `parts` read a geometry apart,
`measures` answers areas and distances, `predicates` answers the OGC relations,
`transforms` moves and reprojects, `linear` addresses positions along a chain, and
`grid` turns a position into a group key.
"""

from __future__ import annotations

from batcher.plan.functions.geo.accessors import (
    st_coord_dim,
    st_dimension,
    st_geometry_type,
    st_num_geometries,
    st_num_interior_rings,
    st_num_points,
    st_set_srid,
    st_srid,
    st_x,
    st_xmax,
    st_xmin,
    st_y,
    st_ymax,
    st_ymin,
    st_z,
)
from batcher.plan.functions.geo.codecs import (
    st_as_binary,
    st_as_ewkb,
    st_as_ewkt,
    st_as_geojson,
    st_as_hex_wkb,
    st_as_text,
    st_geom_from_geohash,
    st_geom_from_geojson,
    st_geom_from_text,
    st_geom_from_wkb,
)
from batcher.plan.functions.geo.construct import (
    st_boundary,
    st_buffer,
    st_centroid,
    st_collect,
    st_convex_hull,
    st_envelope,
    st_expand,
    st_make_envelope,
    st_make_line,
    st_make_polygon,
    st_point,
    st_point_on_surface,
    st_point_z,
)
from batcher.plan.functions.geo.grid import (
    geohash_decode_lat,
    geohash_decode_lon,
    geohash_encode,
    st_geohash,
    st_hex_bin,
    st_hex_center_x,
    st_hex_center_y,
    st_quadkey,
    st_s2_cell,
    st_s2_cell_parent,
    st_tile_x,
    st_tile_y,
    st_utm_epsg,
    st_utm_zone,
)
from batcher.plan.functions.geo.linear import (
    st_closest_point,
    st_line_interpolate_point,
    st_line_locate_point,
    st_line_substring,
    st_project,
    st_shortest_line,
)
from batcher.plan.functions.geo.measures import (
    st_area,
    st_area_spheroid,
    st_azimuth,
    st_distance,
    st_distance_sphere,
    st_distance_spheroid,
    st_hausdorff_distance,
    st_length,
    st_length_spheroid,
    st_max_distance,
    st_perimeter,
    st_perimeter_spheroid,
)
from batcher.plan.functions.geo.parts import (
    st_end_point,
    st_exterior_ring,
    st_geometry_n,
    st_has_z,
    st_interior_ring_n,
    st_is_closed,
    st_is_collection,
    st_is_empty,
    st_is_ring,
    st_is_simple,
    st_is_valid,
    st_is_valid_reason,
    st_point_n,
    st_start_point,
)
from batcher.plan.functions.geo.predicates import (
    st_contains,
    st_contains_extent,
    st_covered_by,
    st_covers,
    st_crosses,
    st_disjoint,
    st_dwithin,
    st_dwithin_sphere,
    st_equals,
    st_intersects,
    st_intersects_extent,
    st_overlaps,
    st_touches,
    st_within,
)
from batcher.plan.functions.geo.transforms import (
    st_affine,
    st_flip_coordinates,
    st_force_2d,
    st_force_3d,
    st_force_polygon_ccw,
    st_force_polygon_cw,
    st_remove_repeated_points,
    st_reverse,
    st_rotate,
    st_scale,
    st_segmentize,
    st_simplify,
    st_snap_to_grid,
    st_transform,
    st_translate,
)

__all__ = [
    "geohash_decode_lat",
    "geohash_decode_lon",
    "geohash_encode",
    "st_affine",
    "st_area",
    "st_area_spheroid",
    "st_as_binary",
    "st_as_ewkb",
    "st_as_ewkt",
    "st_as_geojson",
    "st_as_hex_wkb",
    "st_as_text",
    "st_azimuth",
    "st_boundary",
    "st_buffer",
    "st_centroid",
    "st_closest_point",
    "st_collect",
    "st_contains",
    "st_contains_extent",
    "st_convex_hull",
    "st_coord_dim",
    "st_covered_by",
    "st_covers",
    "st_crosses",
    "st_dimension",
    "st_disjoint",
    "st_distance",
    "st_distance_sphere",
    "st_distance_spheroid",
    "st_dwithin",
    "st_dwithin_sphere",
    "st_end_point",
    "st_envelope",
    "st_equals",
    "st_expand",
    "st_exterior_ring",
    "st_flip_coordinates",
    "st_force_2d",
    "st_force_3d",
    "st_force_polygon_ccw",
    "st_force_polygon_cw",
    "st_geohash",
    "st_geom_from_geohash",
    "st_geom_from_geojson",
    "st_geom_from_text",
    "st_geom_from_wkb",
    "st_geometry_n",
    "st_geometry_type",
    "st_has_z",
    "st_hausdorff_distance",
    "st_hex_bin",
    "st_hex_center_x",
    "st_hex_center_y",
    "st_interior_ring_n",
    "st_intersects",
    "st_intersects_extent",
    "st_is_closed",
    "st_is_collection",
    "st_is_empty",
    "st_is_ring",
    "st_is_simple",
    "st_is_valid",
    "st_is_valid_reason",
    "st_length",
    "st_length_spheroid",
    "st_line_interpolate_point",
    "st_line_locate_point",
    "st_line_substring",
    "st_make_envelope",
    "st_make_line",
    "st_make_polygon",
    "st_max_distance",
    "st_num_geometries",
    "st_num_interior_rings",
    "st_num_points",
    "st_overlaps",
    "st_perimeter",
    "st_perimeter_spheroid",
    "st_point",
    "st_point_n",
    "st_point_on_surface",
    "st_point_z",
    "st_project",
    "st_quadkey",
    "st_remove_repeated_points",
    "st_reverse",
    "st_rotate",
    "st_s2_cell",
    "st_s2_cell_parent",
    "st_scale",
    "st_segmentize",
    "st_set_srid",
    "st_shortest_line",
    "st_simplify",
    "st_snap_to_grid",
    "st_srid",
    "st_start_point",
    "st_tile_x",
    "st_tile_y",
    "st_touches",
    "st_transform",
    "st_translate",
    "st_utm_epsg",
    "st_utm_zone",
    "st_within",
    "st_x",
    "st_xmax",
    "st_xmin",
    "st_y",
    "st_ymax",
    "st_ymin",
    "st_z",
]
