"""Typing declarations for the methods bound onto expression classes at runtime.

GENERATED by `tools/gen_bound_decls.py` from the live classes. Do not edit; run
`just gen-decls`. `tests/unit/test_bound_decls.py` fails when this file is stale.

Each class here declares, for type checkers and editors only, the methods one runtime class
gains through `setattr`. That class inherits these declarations under ``TYPE_CHECKING`` and
`object` otherwise, so nothing here runs or is reachable at runtime.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import NoReturn

    from batcher.plan.expr_ir.core import Expr, IntoExpr, Math2Expr, MathExpr

__all__ = ["AggExprBound", "CaseBuilderBound", "DtBound", "ListBound", "StrBound"]


class StrBound:
    """The methods `batcher.plan.expr_ir.namespaces.strings._StrNamespace` gains at runtime."""

    def lower(self) -> Expr:
        """The string with every letter lowercased, by full Unicode case mapping."""

    def reverse(self) -> Expr:
        """Return each string with its characters reversed."""

    def upper(self) -> Expr:
        """The string with every letter uppercased, by full Unicode case mapping."""


class DtBound:
    """The methods `batcher.plan.expr_ir.namespaces.temporal._DtNamespace` gains at runtime."""

    def century(self) -> Expr:
        """The century, e.g. 2021 → 21."""

    def day(self) -> Expr:
        """The day-of-month component, 1-31."""

    def dayofyear(self) -> Expr:
        """The day of year, 1 through 366."""

    def decade(self) -> Expr:
        """The decade, e.g. 2021 → 202."""

    def epoch(self) -> Expr:
        """Seconds since the Unix epoch, 1970-01-01 00:00:00 UTC (→ Int64)."""

    def hour(self) -> Expr:
        """The hour-of-day component, 0-23."""

    def millennium(self) -> Expr:
        """The millennium, e.g. 2021 → 3."""

    def minute(self) -> Expr:
        """The minute-of-hour component, 0-59."""

    def month(self) -> Expr:
        """The month-of-year component, 1-12."""

    def quarter(self) -> Expr:
        """The calendar quarter, 1-4."""

    def second(self) -> Expr:
        """The second-of-minute component, 0-59."""

    def week(self) -> Expr:
        """The ISO 8601 week number, 1-53."""

    def weekday(self) -> Expr:
        """The ISO day of week, Monday = 1 through Sunday = 7."""

    def year(self) -> Expr:
        """The year component, e.g. 2021."""


class ListBound:
    """The methods `batcher.plan.expr_ir.namespaces.collections._ListNamespace` gains at runtime."""

    def arg_max(self) -> Expr:
        """The 0-based index of the largest element of each list (→ Int64)."""

    def arg_min(self) -> Expr:
        """The 0-based index of the smallest element of each list (→ Int64)."""

    def arg_sort(self) -> Expr:
        """The 0-based indices that sort each list ascending (→ list of Int64)."""

    def cum_sum(self) -> Expr:
        """The cumulative sum of each list — element ``i`` sums ``0..=i`` (→ same-length list)."""

    def diff(self) -> Expr:
        """The first difference of each list (→ list of the same length)."""

    def entropy(self) -> Expr:
        """Shannon entropy of each list read as a distribution, in nats (→ Float64)."""

    def l1_norm(self) -> Expr:
        """The Manhattan (L1) norm, sum of absolute values, of each list (→ Float64)."""

    def l2_norm(self) -> Expr:
        """The Euclidean norm, sqrt(sum of squares), of each list (→ Float64)."""

    def len(self) -> Expr:
        """The number of elements in each list (→ Int64)."""

    def log_softmax(self) -> Expr:
        """Log-softmax over each list — the log-domain distribution, in nats (→ list)."""

    def max(self) -> Expr:
        """The largest element of each list."""

    def max_abs(self) -> Expr:
        """The maximum absolute value of each list — the MaxAbs scaling divisor (→ Float64)."""

    def mean(self) -> Expr:
        """The arithmetic mean of the elements of each list (→ Float64)."""

    def median(self) -> Expr:
        """The median of the elements of each list (→ Float64)."""

    def min(self) -> Expr:
        """The smallest element of each list."""

    def normalize(self) -> Expr:
        """Each list L2-normalized to unit length (→ list); embedding prep."""

    def product(self) -> Expr:
        """The product of the elements of each list."""

    def reverse(self) -> Expr:
        """Return each list with its elements reversed."""

    def softmax(self) -> Expr:
        """Softmax over each list — logits to a probability distribution summing to 1 (→ list)."""


class AggExprBound:
    """The methods `batcher.plan.expr_ir.core.AggExpr` gains at runtime."""

    def abs(self) -> MathExpr:
        """Absolute value, preserving the input numeric dtype (nulls propagate)."""

    def cbrt(self) -> MathExpr:
        """Cube root (→ Float64; defined for negatives, unlike :meth:`sqrt`; nulls propagate)."""

    def ceil(self) -> MathExpr:
        """Round up toward positive infinity to the nearest integer value (nulls propagate)."""

    def clip(self, lower: IntoExpr | None = None, upper: IntoExpr | None = None) -> Expr:
        """Clamp values into ``[lower, upper]`` (either bound optional)."""

    def exp(self) -> MathExpr:
        """``e`` raised to this value, the inverse of :meth:`ln` (→ Float64; nulls propagate)."""

    def expm1(self) -> Expr:
        """``e**x - 1``, accurate for small ``x`` (→ Float64; nulls propagate)."""

    def floor(self) -> MathExpr:
        """Round down toward negative infinity to the nearest integer value (nulls propagate)."""

    def ln(self) -> MathExpr:
        """Natural logarithm, base e (→ Float64). Non-positive inputs yield NaN/-inf; nulls keep."""

    def log10(self) -> MathExpr:
        """Base-10 logarithm (→ Float64). Non-positive inputs yield NaN/-inf; nulls propagate."""

    def log1p(self) -> Expr:
        """Natural log of ``1 + x``, accurate for small ``x`` (→ Float64; nulls propagate)."""

    def log2(self) -> MathExpr:
        """Base-2 logarithm (→ Float64). Non-positive inputs yield NaN/-inf; nulls propagate."""

    def round(self, digits: int | None = None, *, mode: str = "half_away_from_zero") -> Expr:
        """Round to the nearest integer, or to `digits` decimal places."""

    def sign(self) -> MathExpr:
        """Sign of the value as ``-1.0``, ``0.0``, or ``1.0`` (→ Float64; nulls propagate)."""

    def sqrt(self) -> MathExpr:
        """Square root (→ Float64). Negative inputs yield NaN; nulls propagate."""

    def square(self) -> Expr:
        """Each value squared, i.e. ``x * x`` (dtype preserved; nulls propagate)."""

    def trunc(self) -> MathExpr:
        """Truncate toward zero, dropping the fractional part (→ Float64; nulls propagate)."""


class CaseBuilderBound:
    """The methods `batcher.plan.expr_ir.nodes.CaseBuilder` gains at runtime."""

    def __abs__(self) -> MathExpr:
        """Absolute value ``abs(x)`` (Python ``abs()`` protocol)."""

    def __add__(self, other: IntoExpr) -> Expr:
        """Element-wise numeric addition (``a + b``); join strings with ``bt.concat`` instead."""

    def __and__(self, other: IntoExpr) -> Expr:
        """Boolean AND of two predicates (``a & b``), following SQL three-valued logic."""

    def __bool__(self) -> bool:
        """Guard against using an expression in a boolean context."""

    def __ceil__(self) -> MathExpr:
        """``math.ceil(expr)`` — round toward positive infinity."""

    def __contains__(self, item: object) -> NoReturn:
        """Refuse ``x in expr``: the membership operators are `is_in` and `str.contains`."""

    def __divmod__(self, other: IntoExpr) -> tuple[Expr, Expr]:
        """``divmod(a, b)`` — the ``(a // b, a % b)`` pair, as Python defines it."""

    def __eq__(self, other: IntoExpr | None) -> Expr:  # type: ignore[override]
        """Element-wise equality (``a == b``), yielding a boolean expression (not a Python bool)."""

    def __floor__(self) -> MathExpr:
        """``math.floor(expr)`` — round toward negative infinity."""

    def __floordiv__(self, other: IntoExpr) -> Expr:
        """Floor division ``a // b`` — the quotient rounded toward negative infinity."""

    def __ge__(self, other: IntoExpr) -> Expr:
        """Element-wise greater-than-or-equal (``a >= b``), yielding a boolean expression."""

    def __getitem__(self, key: int | slice | str) -> Expr:
        """Index into a list or struct column with ``[]`` (delegates to ``.list``/``.struct``)."""

    def __gt__(self, other: IntoExpr) -> Expr:
        """Element-wise greater-than (``a > b``), yielding a boolean expression."""

    def __hash__(self) -> NoReturn:
        """Refuse hashing: ``==`` builds an expression, so equality-based lookup is a trap."""

    def __invert__(self) -> Expr:
        """Boolean NOT of a predicate (``~a``), following SQL three-valued logic."""

    def __iter__(self) -> NoReturn:
        """Refuse iteration: an expression is a scalar column, not a sequence."""

    def __le__(self, other: IntoExpr) -> Expr:
        """Element-wise less-than-or-equal (``a <= b``), yielding a boolean expression."""

    def __len__(self) -> NoReturn:
        """Refuse `len`: an expression describes a column, it does not hold one yet."""

    def __lshift__(self, other: IntoExpr) -> Expr:
        """Left shift ``a << b``; the operator spelling of :meth:`bitwise_left_shift`."""

    def __lt__(self, other: IntoExpr) -> Expr:
        """Element-wise less-than (``a < b``), yielding a boolean expression."""

    def __matmul__(self, other: IntoExpr) -> Expr:
        """``a @ b`` — the dot product of two list (embedding) columns."""

    def __mod__(self, other: IntoExpr) -> Expr:
        """Element-wise modulo / remainder (``a % b``)."""

    def __mul__(self, other: IntoExpr) -> Expr:
        """Element-wise multiplication (``a * b``)."""

    def __ne__(self, other: IntoExpr | None) -> Expr:  # type: ignore[override]
        """Element-wise inequality (``a != b``), yielding a boolean expression."""

    def __neg__(self) -> Expr:
        """Arithmetic negation ``-x`` (desugars to ``0 - x``; type-preserving)."""

    def __or__(self, other: IntoExpr) -> Expr:
        """Boolean OR of two predicates (``a | b``), following SQL three-valued logic."""

    def __pos__(self) -> Expr:
        """Unary plus ``+x`` — the identity, returning this expression unchanged."""

    def __pow__(self, other: IntoExpr) -> Math2Expr:
        """Exponentiation (``a ** b``, → Float64); the operator spelling of :meth:`pow`."""

    def __radd__(self, other: IntoExpr) -> Expr:
        """Reflected addition so ``scalar + expr`` works (also string concat on Utf8)."""

    def __rand__(self, other: IntoExpr) -> Expr:
        """Reflected boolean AND so ``scalar & expr`` works."""

    def __rdivmod__(self, other: IntoExpr) -> tuple[Expr, Expr]:
        """Reflected `divmod` so ``divmod(scalar, expr)`` works."""

    def __rfloordiv__(self, other: IntoExpr) -> Expr:
        """Reflected floor division so ``scalar // expr`` works; see :meth:`__floordiv__`."""

    def __rlshift__(self, other: IntoExpr) -> Expr:
        """Reflected left shift so ``scalar << expr`` works."""

    def __rmod__(self, other: IntoExpr) -> Expr:
        """Reflected modulo so ``scalar % expr`` works."""

    def __rmul__(self, other: IntoExpr) -> Expr:
        """Reflected multiplication so ``scalar * expr`` works."""

    def __ror__(self, other: IntoExpr) -> Expr:
        """Reflected boolean OR so ``scalar | expr`` works."""

    def __round__(self, ndigits: int | None = None) -> Expr:
        """Python ``round(expr)`` / ``round(expr, n)`` → :meth:`round`."""

    def __rpow__(self, other: IntoExpr) -> Math2Expr:
        """Reflected exponentiation so ``scalar ** expr`` works (→ Float64)."""

    def __rrshift__(self, other: IntoExpr) -> Expr:
        """Reflected right shift so ``scalar >> expr`` works."""

    def __rshift__(self, other: IntoExpr) -> Expr:
        """Right shift ``a >> b``; the operator spelling of :meth:`bitwise_right_shift`."""

    def __rsub__(self, other: IntoExpr) -> Expr:
        """Reflected subtraction so ``scalar - expr`` works."""

    def __rtruediv__(self, other: IntoExpr) -> Expr:
        """Reflected true division so ``scalar / expr`` works (→ Float64)."""

    def __rxor__(self, other: IntoExpr) -> Expr:
        """Reflected XOR so ``scalar ^ expr`` works (boolean or bitwise, as :meth:`__xor__`)."""

    def __sub__(self, other: IntoExpr) -> Expr:
        """Element-wise subtraction (``a - b``)."""

    def __truediv__(self, other: IntoExpr) -> Expr:
        """Element-wise true division (``a / b``, → Float64); ``//`` is :meth:`__floordiv__`."""

    def __trunc__(self) -> MathExpr:
        """``math.trunc(expr)`` — round toward zero."""

    def __xor__(self, other: IntoExpr) -> Expr:
        """Exclusive or ``a ^ b``: boolean over two booleans, else bitwise over Int64."""
