"""Method-form spellings of the `Expr` operators (the pandas ``Series.add`` family).

Every operator on `Expr` already has its natural Python spelling (``a + b``,
``a & b``). pandas additionally exposes each as a *named method* — ``s.add(1)``,
``s.eq(1)`` — and code ported from pandas, or generated by a tool that cannot emit
operators, reaches for those names. Each function here delegates straight to the
dunder, so the built plan is byte-identical to the operator spelling.

These are bound onto `Expr` by `compat.bind_compat_methods`; they are written as
free functions here so `core.py` stays the one-`Expr` hierarchy rather than growing
a second, parallel copy of its own operator surface.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from batcher.plan.expr_ir.core import Expr, IntoExpr

__all__ = [
    "add",
    "and_",
    "div",
    "eq",
    "floordiv",
    "ge",
    "gt",
    "le",
    "lt",
    "mod",
    "mul",
    "ne",
    "not_",
    "or_",
    "sub",
    "truediv",
    "xor",
]


def add(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise addition — the pandas ``add`` spelling of the ``+`` operator.

    Args:
        other: The value or expression to add.

    Returns:
        A new expression computing ``self + other``.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 2]})
            >>> ds.select(r=bt.col("x").add(10)).to_pydict()
            {'r': [11, 12]}
    """
    return self + other


def sub(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise subtraction — the pandas ``sub`` spelling of the ``-`` operator.

    Args:
        other: The value or expression to subtract.

    Returns:
        A new expression computing ``self - other``.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 2]})
            >>> ds.select(r=bt.col("x").sub(1)).to_pydict()
            {'r': [0, 1]}
    """
    return self - other


def mul(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise multiplication — the pandas ``mul`` spelling of the ``*`` operator.

    Args:
        other: The value or expression to multiply by.

    Returns:
        A new expression computing ``self * other``.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 2]})
            >>> ds.select(r=bt.col("x").mul(3)).to_pydict()
            {'r': [3, 6]}
    """
    return self * other


def truediv(self: Expr, other: IntoExpr) -> Expr:
    """True division — the pandas ``truediv`` spelling of the ``/`` operator (to Float64).

    Integer operands divide truly rather than truncating, matching Python, Polars
    and DuckDB.

    Args:
        other: The value or expression to divide by.

    Returns:
        A new Float64 expression computing ``self / other``.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 3]})
            >>> ds.select(r=bt.col("x").truediv(2)).to_pydict()
            {'r': [0.5, 1.5]}
    """
    return self / other


def div(self: Expr, other: IntoExpr) -> Expr:
    """True division — the pandas ``div`` alias of :meth:`truediv` (to Float64).

    Args:
        other: The value or expression to divide by.

    Returns:
        A new Float64 expression computing ``self / other``.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 3]})
            >>> ds.select(r=bt.col("x").div(2)).to_pydict()
            {'r': [0.5, 1.5]}
    """
    return self / other


def floordiv(self: Expr, other: IntoExpr) -> Expr:
    """Floor division — the pandas ``floordiv`` spelling of the ``//`` operator.

    Rounds toward negative infinity (Python/Polars semantics), and is
    type-preserving for integers.

    Args:
        other: The value or expression to divide by.

    Returns:
        A new expression computing ``self // other``.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [7, -7]})
            >>> ds.select(r=bt.col("x").floordiv(3)).to_pydict()
            {'r': [2, -3]}
    """
    return self // other


def mod(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise remainder — the pandas ``mod`` spelling of the ``%`` operator.

    Args:
        other: The value or expression to take the remainder against.

    Returns:
        A new expression computing ``self % other``.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [7, 8]})
            >>> ds.select(r=bt.col("x").mod(3)).to_pydict()
            {'r': [1, 2]}
    """
    return self % other


def eq(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise equality — the pandas ``eq`` spelling of the ``==`` operator.

    Args:
        other: The value or expression to compare against.

    Returns:
        A boolean expression, true where the values are equal.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 2]})
            >>> ds.select(r=bt.col("x").eq(1)).to_pydict()
            {'r': [True, False]}
    """
    return self == other


def ne(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise inequality — the pandas ``ne`` spelling of the ``!=`` operator.

    Args:
        other: The value or expression to compare against.

    Returns:
        A boolean expression, true where the values differ.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 2]})
            >>> ds.select(r=bt.col("x").ne(1)).to_pydict()
            {'r': [False, True]}
    """
    return self != other


def lt(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise less-than — the pandas ``lt`` spelling of the ``<`` operator.

    Args:
        other: The value or expression to compare against.

    Returns:
        A boolean expression, true where `self` is smaller.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 2, 3]})
            >>> ds.select(r=bt.col("x").lt(2)).to_pydict()
            {'r': [True, False, False]}
    """
    return self < other


def le(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise less-or-equal — the pandas ``le`` spelling of the ``<=`` operator.

    Args:
        other: The value or expression to compare against.

    Returns:
        A boolean expression, true where `self` is smaller or equal.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 2, 3]})
            >>> ds.select(r=bt.col("x").le(2)).to_pydict()
            {'r': [True, True, False]}
    """
    return self <= other


def gt(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise greater-than — the pandas ``gt`` spelling of the ``>`` operator.

    Args:
        other: The value or expression to compare against.

    Returns:
        A boolean expression, true where `self` is larger.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 2, 3]})
            >>> ds.select(r=bt.col("x").gt(2)).to_pydict()
            {'r': [False, False, True]}
    """
    return self > other


def ge(self: Expr, other: IntoExpr) -> Expr:
    """Element-wise greater-or-equal — the pandas ``ge`` spelling of the ``>=`` operator.

    Args:
        other: The value or expression to compare against.

    Returns:
        A boolean expression, true where `self` is larger or equal.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [1, 2, 3]})
            >>> ds.select(r=bt.col("x").ge(2)).to_pydict()
            {'r': [False, True, True]}
    """
    return self >= other


def and_(self: Expr, other: IntoExpr) -> Expr:
    """Boolean AND — the named spelling of the ``&`` operator (SQL three-valued logic).

    Python's ``and`` keyword cannot be overloaded, so this is the spelling for code
    that cannot use the operator form.

    Args:
        other: The predicate to AND with.

    Returns:
        A boolean expression, true where both predicates hold.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"a": [True, True], "b": [True, False]})
            >>> ds.select(r=bt.col("a").and_(bt.col("b"))).to_pydict()
            {'r': [True, False]}
    """
    return self & other


def or_(self: Expr, other: IntoExpr) -> Expr:
    """Boolean OR — the named spelling of the ``|`` operator (SQL three-valued logic).

    Args:
        other: The predicate to OR with.

    Returns:
        A boolean expression, true where either predicate holds.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"a": [True, False], "b": [False, False]})
            >>> ds.select(r=bt.col("a").or_(bt.col("b"))).to_pydict()
            {'r': [True, False]}
    """
    return self | other


def not_(self: Expr) -> Expr:
    """Boolean NOT — the named spelling of the ``~`` operator (SQL three-valued logic).

    Returns:
        A boolean expression, true where the predicate is false.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"a": [True, False]})
            >>> ds.select(r=bt.col("a").not_()).to_pydict()
            {'r': [False, True]}
    """
    return ~self


def xor(self: Expr, other: IntoExpr) -> Expr:
    """Bitwise XOR — the named spelling of the ``^`` operator (operands cast to Int64).

    Args:
        other: The integer expression or value to XOR with.

    Returns:
        A new expression of the XORed bit patterns.

    Examples:
        .. doctest::

            >>> import batcher as bt
            >>> ds = bt.from_pydict({"x": [6]})
            >>> ds.select(r=bt.col("x").xor(3)).to_pydict()
            {'r': [5]}
    """
    return self ^ other
