"""ML data plane — actor-pool batch inference, training ingest, and preprocessing.

Control-plane orchestration (model-once-per-worker pools, dynamic batching) over whole
Arrow batches; the native-pipeline foundation lives in the Rust `bc-udf` crate. Also
re-exports the sklearn-style `Preprocessor` family, whose `fit` learns state with one
mergeable aggregate and whose `transform` is a lazy `Expr` projection.
"""

from __future__ import annotations

from batcher.ml.cluster import KMeans, NearestCentroid
from batcher.ml.converters import to_numpy_batches, to_tf_dataset, to_torch_iterable
from batcher.ml.corpus import (
    MixtureReport,
    QualityThresholds,
    contamination_rate,
    decontaminate,
    length_grouped_order,
    mix_corpora,
    padding_waste,
    quality_filter,
    quality_flags,
    quality_report,
)
from batcher.ml.discriminant import (
    LinearDiscriminantAnalysis,
    QuadraticDiscriminantAnalysis,
)
from batcher.ml.dummy import DummyClassifier, DummyRegressor
from batcher.ml.embed import EncoderFactory, build_vector_index, embed, vector_search
from batcher.ml.embed_api import openai_embedding_encoder, tei_encoder
from batcher.ml.feature_spec import FeatureSpec
from batcher.ml.glm import GammaRegressor, PoissonRegressor, TweedieRegressor
from batcher.ml.inference import InferencePool, Worker, WorkerFactory
from batcher.ml.interpret import partial_dependence, permutation_importance
from batcher.ml.linear import (
    LinearRegression,
    LogisticRegression,
    Ridge,
    RidgeClassifier,
)
from batcher.ml.llm import (
    Engine,
    EngineFactory,
    anthropic_engine,
    http_engine,
    json_schema,
    llm_generate,
    llm_pairwise_udf,
    llm_score_udf,
    llm_udf,
    llm_verify_udf,
    pack_sequences,
    vllm_engine,
)
from batcher.ml.loader import (
    iter_torch_batches,
    shard_stream_loader,
    stream_loader,
    streaming_split,
)
from batcher.ml.mixture import GaussianMixture
from batcher.ml.model_selection import cross_val_predict, cross_val_score, learning_curve
from batcher.ml.naive_bayes import BernoulliNB, GaussianNB, MultinomialNB
from batcher.ml.outliers import (
    OutlierClipper,
    count_outliers,
    flag_outliers,
    mahalanobis_distance,
    outlier_bounds,
)
from batcher.ml.pipeline import Stage, run_pipeline
from batcher.ml.preprocessors import (
    PCA,
    Binarizer,
    BinaryEncoder,
    BoxCoxTransformer,
    Chain,
    Clipper,
    ColumnDropper,
    ColumnSelector,
    Concatenator,
    CyclicalEncoder,
    DateTimeFeaturizer,
    FrequencyEncoder,
    GroupImputer,
    GroupStatEncoder,
    HashingEncoder,
    InteractionFeatures,
    KBinsDiscretizer,
    LabelBinarizer,
    LabelEncoder,
    LagFeaturizer,
    LogTransformer,
    MaxAbsScaler,
    MinMaxScaler,
    MissingIndicator,
    MultiHotEncoder,
    MultiLabelBinarizer,
    Normalizer,
    OneHotEncoder,
    OrdinalEncoder,
    PolynomialFeatures,
    PowerTransformer,
    Preprocessor,
    QuantileTransformer,
    RankTransformer,
    RareCategoryEncoder,
    RatioFeatures,
    RobustScaler,
    RollingFeaturizer,
    SimpleImputer,
    StandardScaler,
    TargetEncoder,
    TextStatFeaturizer,
    Tokenizer,
    TruncatedSVD,
    VarianceThreshold,
    WOEEncoder,
    from_dict,
    load,
    save,
    to_dict,
)
from batcher.ml.retrieval import mmr_rerank_udf
from batcher.ml.sampling import (
    balanced_sample,
    class_counts,
    class_weights,
    oversample,
    sample_weights,
    stratified_sample,
    undersample,
)
from batcher.ml.serving import (
    ServingClient,
    http_client,
    serve_deployment,
    serving_udf,
    torchserve_client,
    triton_client,
)
from batcher.ml.sparse_linear import ElasticNet, Lasso
from batcher.ml.streaming_sampler import (
    ResumableSampler,
    epoch_order,
    epoch_permutation,
    rank_index_batches,
    usable_length,
)

__all__ = [
    "PCA",
    "BernoulliNB",
    "Binarizer",
    "BinaryEncoder",
    "BoxCoxTransformer",
    "Chain",
    "Clipper",
    "ColumnDropper",
    "ColumnSelector",
    "Concatenator",
    "CyclicalEncoder",
    "DateTimeFeaturizer",
    "DummyClassifier",
    "DummyRegressor",
    "ElasticNet",
    "EncoderFactory",
    "Engine",
    "EngineFactory",
    "FeatureSpec",
    "FrequencyEncoder",
    "GammaRegressor",
    "GaussianMixture",
    "GaussianNB",
    "GroupImputer",
    "GroupStatEncoder",
    "HashingEncoder",
    "InferencePool",
    "InteractionFeatures",
    "KBinsDiscretizer",
    "KMeans",
    "LabelBinarizer",
    "LabelEncoder",
    "LagFeaturizer",
    "Lasso",
    "LinearDiscriminantAnalysis",
    "LinearRegression",
    "LogTransformer",
    "LogisticRegression",
    "MaxAbsScaler",
    "MinMaxScaler",
    "MissingIndicator",
    "MixtureReport",
    "MultiHotEncoder",
    "MultiLabelBinarizer",
    "MultinomialNB",
    "NearestCentroid",
    "Normalizer",
    "OneHotEncoder",
    "OrdinalEncoder",
    "OutlierClipper",
    "PoissonRegressor",
    "PolynomialFeatures",
    "PowerTransformer",
    "Preprocessor",
    "QuadraticDiscriminantAnalysis",
    "QualityThresholds",
    "QuantileTransformer",
    "RankTransformer",
    "RareCategoryEncoder",
    "RatioFeatures",
    "ResumableSampler",
    "Ridge",
    "RidgeClassifier",
    "RobustScaler",
    "RollingFeaturizer",
    "ServingClient",
    "SimpleImputer",
    "Stage",
    "StandardScaler",
    "TargetEncoder",
    "TextStatFeaturizer",
    "Tokenizer",
    "TruncatedSVD",
    "TweedieRegressor",
    "VarianceThreshold",
    "WOEEncoder",
    "Worker",
    "WorkerFactory",
    "anthropic_engine",
    "balanced_sample",
    "build_vector_index",
    "class_counts",
    "class_weights",
    "contamination_rate",
    "count_outliers",
    "cross_val_predict",
    "cross_val_score",
    "decontaminate",
    "embed",
    "epoch_order",
    "epoch_permutation",
    "flag_outliers",
    "from_dict",
    "http_client",
    "http_engine",
    "iter_torch_batches",
    "json_schema",
    "learning_curve",
    "length_grouped_order",
    "llm_generate",
    "llm_pairwise_udf",
    "llm_score_udf",
    "llm_udf",
    "llm_verify_udf",
    "load",
    "mahalanobis_distance",
    "mix_corpora",
    "mmr_rerank_udf",
    "openai_embedding_encoder",
    "outlier_bounds",
    "oversample",
    "pack_sequences",
    "padding_waste",
    "partial_dependence",
    "permutation_importance",
    "quality_filter",
    "quality_flags",
    "quality_report",
    "rank_index_batches",
    "run_pipeline",
    "sample_weights",
    "save",
    "serve_deployment",
    "serving_udf",
    "shard_stream_loader",
    "stratified_sample",
    "stream_loader",
    "streaming_split",
    "tei_encoder",
    "to_dict",
    "to_numpy_batches",
    "to_tf_dataset",
    "to_torch_iterable",
    "torchserve_client",
    "triton_client",
    "undersample",
    "usable_length",
    "vector_search",
    "vllm_engine",
]
