"""The expression function library, grouped by family.

These are the broader SQL/PySpark/DuckDB-style free functions (string, conditional,
math, …), built by composing the core `Expr` nodes from `batcher.plan.expr_ir`.
They are kept separate from `expr_ir.constructors` (which holds the primitive
constructors tied directly to the node classes — `col`/`lit`/`when`/…) so this
package can grow by family without bloating the core module. Surfaced to users
through the `batcher.api.functions` façade.
"""

from __future__ import annotations

from batcher.plan.functions.aggregate import (
    corr,
    count_if,
    covar_pop,
    covar_samp,
    max,
    mean,
    median,
    min,
    n_unique,
    std,
    sum,
    var,
)
from batcher.plan.functions.collection import element, named_struct, sequence, struct
from batcher.plan.functions.horizontal import (
    all_horizontal,
    any_horizontal,
    count_horizontal,
    fold_horizontal,
    max_horizontal,
    mean_horizontal,
    min_horizontal,
    product_horizontal,
    reduce_horizontal,
    sum_horizontal,
)
from batcher.plan.functions.prompt import (
    chatml_prompt,
    conversation_turns,
    ends_with_role,
    fits_context,
    instruction_prompt,
    join_context,
    last_message,
    prompt_token_estimate,
    render_messages,
    render_template,
    tagged_fields,
    truncate_middle,
    truncate_to_token_budget,
    wrap_tag,
)
from batcher.plan.functions.scalar import (
    arctan2,
    gcd,
    great_circle_distance,
    hypot,
    iff,
    lcm,
    log,
    nanvl,
    next_after,
    width_bucket,
)
from batcher.plan.functions.security import aes_decrypt, aes_encrypt, hmac_sha256, mask
from batcher.plan.functions.string import (
    concat,
    concat_ws,
    extract_after,
    extract_between,
    extract_choice,
    extract_code_block,
    extract_first_number,
    extract_json,
    extract_json_array,
    extract_reasoning,
    extract_tag,
    format_string,
    is_refusal,
    strip_reasoning,
)
from batcher.plan.functions.temporal import (
    current_date,
    current_timestamp,
    date_add,
    date_part,
    date_sub,
    from_epoch,
    from_unix_date,
    make_date,
    make_timestamp,
    window,
)

__all__ = [
    "aes_decrypt",
    "aes_encrypt",
    "all_horizontal",
    "any_horizontal",
    "arctan2",
    "chatml_prompt",
    "concat",
    "concat_ws",
    "conversation_turns",
    "corr",
    "count_horizontal",
    "count_if",
    "covar_pop",
    "covar_samp",
    "current_date",
    "current_timestamp",
    "date_add",
    "date_part",
    "date_sub",
    "element",
    "ends_with_role",
    "extract_after",
    "extract_between",
    "extract_choice",
    "extract_code_block",
    "extract_first_number",
    "extract_json",
    "extract_json_array",
    "extract_reasoning",
    "extract_tag",
    "fits_context",
    "fold_horizontal",
    "format_string",
    "from_epoch",
    "from_unix_date",
    "gcd",
    "great_circle_distance",
    "hmac_sha256",
    "hypot",
    "iff",
    "instruction_prompt",
    "is_refusal",
    "join_context",
    "last_message",
    "lcm",
    "log",
    "make_date",
    "make_timestamp",
    "mask",
    "max",
    "max_horizontal",
    "mean",
    "mean_horizontal",
    "median",
    "min",
    "min_horizontal",
    "n_unique",
    "named_struct",
    "nanvl",
    "next_after",
    "product_horizontal",
    "prompt_token_estimate",
    "reduce_horizontal",
    "render_messages",
    "render_template",
    "sequence",
    "std",
    "strip_reasoning",
    "struct",
    "sum",
    "sum_horizontal",
    "tagged_fields",
    "truncate_middle",
    "truncate_to_token_budget",
    "var",
    "width_bucket",
    "window",
    "wrap_tag",
]
