"""Shared accessor-generation helper for the namespace families.

The parameterless accessor families (string transforms, date fields, list
reductions) are **data, not code**: each is one row in a dispatch table, with the
no-argument accessor generated by `_bind_accessors`.
"""

from __future__ import annotations

import inspect
import sys
import types
from collections.abc import Callable
from typing import Any

from batcher.plan.expr_ir.core import Expr
from batcher.plan.expr_ir.namespaces._descriptions import _DESCRIPTIONS

# The public signature every generated accessor advertises: it takes nothing and
# returns an `Expr`. The `_tag`/`_build` defaults the factory closes over are
# implementation, and without this Sphinx renders them —
# ``upper(_tag='upper', _build=<function <lambda>>)`` — into the user's reference page.
_ACCESSOR_SIGNATURE = inspect.Signature(
    [inspect.Parameter("self", inspect.Parameter.POSITIONAL_OR_KEYWORD)],
    return_annotation=Expr,
)


def _with_returns(body: str, returns: str) -> str:
    """Splice a family-wide ``Returns:`` section into a bound accessor's docstring.

    The parameterless accessors take no caller argument, so the section order is
    simply ``summary → Returns: → Examples:`` — the house order in
    ``api/dataset/frame.py``, where the typed sections precede ``Examples:``. The
    ``returns`` text is identical for every accessor in a family, so it is supplied
    once by the caller instead of being repeated in every ``_DESCRIPTIONS`` entry.
    """
    block = f"Returns:\n    {returns}"
    marker = "\nExamples:"
    idx = body.find(marker)
    if idx == -1:
        return f"{body}\n\n{block}"
    return f"{body[:idx].rstrip()}\n\n{block}\n\n{body[idx:].lstrip(chr(10))}"


def _bind_accessors(
    ns: type,
    table: dict[str, str],
    build: Callable[[Expr, str], Expr],
    doc: Callable[[str], str],
    returns: str | Callable[[str], str],
) -> None:
    """Generate one no-argument accessor per `table` row and attach it to `ns`.

    Collapses the three parameterless accessor families (string transforms, date
    fields, list reductions) onto a single factory: each accessor wraps the
    namespace's expression (``self._e``) into ``build(self._e, tag)`` and carries a
    docstring — the curated `_DESCRIPTIONS` entry for `name` when present, else the
    per-family ``doc(name)`` template — with a uniform `returns` section appended by
    the factory (a family-wide string, or a ``name -> text`` callable). The bound
    function is rebuilt in `ns`'s module namespace so ``__module__``/``__globals__``
    match the class; ``doctest`` (and Sphinx autodoc) then discover its examples as
    if it were hand-written there, and `_ACCESSOR_SIGNATURE` hides the injected
    `_tag`/`_build` defaults so the reference page reads ``upper() -> Expr``.
    """
    ns_globals = sys.modules[ns.__module__].__dict__
    for name, tag in table.items():

        def accessor(
            self: Any,
            _tag: str = tag,
            _build: Callable[[Expr, str], Expr] = build,
        ) -> Expr:
            return _build(self._e, _tag)

        bound = types.FunctionType(accessor.__code__, ns_globals, name, accessor.__defaults__)
        bound.__qualname__ = f"{ns.__name__}.{name}"
        bound.__module__ = ns.__module__
        bound.__signature__ = _ACCESSOR_SIGNATURE  # type: ignore[attr-defined]
        ret = returns(name) if callable(returns) else returns
        bound.__doc__ = _with_returns(_DESCRIPTIONS.get(name, doc(name)), ret)
        setattr(ns, name, bound)
