#!/usr/bin/env python3
"""Generate the per-engine migration reference pages from the migration registry.

Batcher keeps one spelling per capability, so a user arriving from PySpark, Polars, Daft or
Ray Data needs a lookup for every name they already type: the Batcher spelling, whether the
two engines compute the same thing, and what is missing or different when they don't. The
migration registry (`python/batcher/_internal/migration/data/<engine>/*.toml`) already holds
that answer for every public name in each engine's snapshot, and the `AttributeError`
guidance reads the same rows. A hand-kept table would be a third copy that drifts.

So the reference pages under `docs/getting-started/migration/<engine>/` are derived, never
written by hand. Each registry file is a family of names, and each page groups one or more
families so that no page passes the 500-line docs limit and no directory passes twelve
pages. Every table row reads in both directions, and `leaving-batcher.md` inverts the rows
whose status says the two engines agree.

Which codemod directions the pages call implemented is read from `_IMPLEMENTED` in
`python/batcher/migrate/__main__.py` by parsing the file, not importing it, so generating the
docs needs neither `libcst` nor a built engine.

Run it::

    python tools/gen_migration_docs.py           # rewrite the pages
    python tools/gen_migration_docs.py --check   # exit 1 if any page is stale

`tests/docs/test_migration_docs_fresh.py` runs the same comparison in the test suite.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
import tomllib
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "python"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import doc_api_links  # noqa: E402  (tools/ is on the path: this file's own directory)

from batcher._internal.migration import (  # noqa: E402
    DATA_DIR,
    OPERATORS,
    Mapping,
    Status,
    load_registry,
)
from batcher._internal.migration.schema import ENGINES as ENGINE_KEYS  # noqa: E402

MIGRATION_DOCS = REPO / "docs" / "getting-started" / "migration"
_CLI = REPO / "python" / "batcher" / "migrate" / "__main__.py"
_SNAPSHOTS = REPO / "tools" / "parity" / "surfaces"
_SURFACES = REPO / "tools" / "parity" / "surfaces.py"

_HEADER = (
    "<!-- Generated by tools/gen_migration_docs.py from the migration registry in "
    "python/batcher/_internal/migration/data/{engine}/. Do not edit by hand: change the "
    "registry, then run `just migration-docs`. -->"
)

# What each status means to a reader, in the order the legend lists them.
_STATUS_MEANING: dict[Status, str] = {
    Status.CANONICAL: "Both engines compute the same thing. Use the Batcher spelling.",
    Status.PARAM: (
        "The capability exists, but Batcher lacks an option the other engine offers. The notes "
        "say which."
    ),
    Status.MISMATCH: (
        "Both engines have the capability and give different answers. The notes say what "
        "differs. Never rename one of these without reading them."
    ),
    Status.GAP: "Batcher has no equivalent yet. The notes say what is missing.",
    Status.OUT_OF_SCOPE: "Batcher deliberately doesn't provide it. The notes say why.",
}

_STATUS_LABEL: dict[Status, str] = {
    Status.CANONICAL: "canonical",
    Status.PARAM: "param",
    Status.MISMATCH: "mismatch",
    Status.GAP: "gap",
    Status.OUT_OF_SCOPE: "out of scope",
}

# The planned delivery waves, summarized from the parity plan's wave table.
_WAVES: dict[str, str] = {
    "WF": (
        "Foundations: output-name inference and aggregate broadcasting in `select`, `when` "
        "without `otherwise`, `over` on every expression, one explicit row-order policy, and "
        "the UDF verbs consolidated onto `Dataset`"
    ),
    "W0": "Silent mismatches: parameters that restore the other engine's semantics",
    "W1": "Python constructors over SQL functions Batcher already has",
    "W2": "Missing parameters across all four engines",
    "W3": "Scalar functions",
    "W4": "Maps, higher-order functions, and list reduction",
    "W5": "Window functions, including rolling and dynamic group-by",
    "W6": "Temporal types: `TIME`, intervals, and a session time zone",
    "W7": "Semi-structured data: JSON, CSV, and XML functions",
    "W8": "Relational `DataFrame` gaps",
    "W9": "Catalogs and tables",
    "W10": "Streaming",
    "W11": "UDFs",
    "W12": "AI and multimodal",
    "W13": "Readers and writers",
    "W14": "Sketches, collations, and the geography type",
}


@dataclass(frozen=True)
class Page:
    """One generated page: a slug, a title, and the registry files it renders."""

    slug: str
    title: str
    files: tuple[str, ...]


@dataclass(frozen=True)
class Engine:
    """One source engine: where its pages go and how its registry files are grouped."""

    key: str
    directory: str
    label: str
    families: dict[str, str]
    pages: tuple[Page, ...]


ENGINES: tuple[Engine, ...] = (
    Engine(
        key="pyspark",
        directory="spark",
        label="PySpark",
        families={
            "column": "column methods",
            "dataframe": "DataFrame and its na and stat helpers",
            "functions_aggregates": "aggregates, window functions, and sketches",
            "functions_collections": "arrays, maps, structs, and semi-structured data",
            "functions_math": "math and bitwise",
            "functions_misc": "conditionals, sorting, UDFs, session, and geospatial",
            "functions_strings": "strings, binary, and hashing",
            "functions_temporal": "dates, times, and partition transforms",
            "grouping_window": "grouping and windows",
            "io": "readers and writers, batch and streaming",
            "session": "session, catalog, configuration, UDF registration, and streaming queries",
            "types_datasource": "types and the Python data source API",
        },
        pages=(
            Page(
                "dataframe",
                "PySpark DataFrame, grouping, and windows",
                ("dataframe", "grouping_window"),
            ),
            Page("expressions", "PySpark column expressions", ("column",)),
            Page(
                "functions-aggregates",
                "PySpark aggregate and window functions",
                ("functions_aggregates",),
            ),
            Page(
                "functions-collections",
                "PySpark collection and semi-structured functions",
                ("functions_collections",),
            ),
            Page(
                "functions-math-and-misc",
                "PySpark math, conditional, and other functions",
                ("functions_math", "functions_misc"),
            ),
            Page(
                "functions-strings",
                "PySpark string, binary, and hash functions",
                ("functions_strings",),
            ),
            Page("functions-temporal", "PySpark date and time functions", ("functions_temporal",)),
            Page("io", "PySpark readers and writers", ("io",)),
            Page(
                "session-and-sql", "PySpark session, catalog, and streaming queries", ("session",)
            ),
            Page("types-and-data-sources", "PySpark types and data sources", ("types_datasource",)),
        ),
    ),
    Engine(
        key="polars",
        directory="polars",
        label="Polars",
        families={
            "expr": "expressions",
            "expr_dt": "the date and time namespace",
            "expr_list_arr": "the list and array namespaces",
            "expr_misc_ns": "the struct, categorical, binary, name, and meta namespaces",
            "expr_str": "the string namespace",
            "frame": "LazyFrame and DataFrame",
            "groupby": "group-by objects",
            "selectors": "selectors",
            "sql_config_api": "SQL context, configuration, and extension registration",
            "toplevel_functions": "functions",
            "toplevel_io": "readers, scanners, and credentials",
            "toplevel_types": "data types",
        },
        pages=(
            Page("dataframe", "Polars LazyFrame, DataFrame, and group-by", ("frame", "groupby")),
            Page("expressions", "Polars expressions", ("expr",)),
            Page(
                "expression-namespaces",
                "Polars expression namespaces",
                ("expr_str", "expr_dt", "expr_list_arr", "expr_misc_ns"),
            ),
            Page(
                "functions", "Polars functions and selectors", ("toplevel_functions", "selectors")
            ),
            Page("io", "Polars readers and scanners", ("toplevel_io",)),
            Page("types", "Polars data types", ("toplevel_types",)),
            Page("session-and-sql", "Polars SQL context and configuration", ("sql_config_api",)),
        ),
    ),
    Engine(
        key="daft",
        directory="daft",
        label="Daft",
        families={
            "dataframe": "DataFrame verbs, grouped aggregation, and the Window spec",
            "datatype": "DataType constructors, predicates, and accessors",
            "multimodal_ai": "image, video, audio, file, and AI functions",
            "nested_misc": "list, map, struct, JSON, embedding, null, cast, and hash functions",
            "numeric_agg": "math, aggregate, and window functions",
            "session_catalog": "Session, Catalog, and Table",
            "string": "string functions",
            "temporal": "date, time, and timestamp functions",
            "toplevel": "constructors, readers, session shortcuts, and UDF decorators",
        },
        pages=(
            Page("dataframe", "Daft DataFrame, grouping, and windows", ("dataframe",)),
            Page("module", "The daft module", ("toplevel",)),
            Page(
                "functions-numeric", "Daft math, aggregate, and window functions", ("numeric_agg",)
            ),
            Page("functions-strings", "Daft string functions", ("string",)),
            Page("functions-temporal", "Daft date and time functions", ("temporal",)),
            Page("functions-nested", "Daft nested, JSON, and other functions", ("nested_misc",)),
            Page("udfs-ai-multimodal", "Daft multimodal and AI functions", ("multimodal_ai",)),
            Page("session-and-catalog", "Daft session and catalog", ("session_catalog",)),
            Page("types", "Daft data types", ("datatype",)),
        ),
    ),
    Engine(
        key="ray_data",
        directory="ray-data",
        label="Ray Data",
        families={
            "aggregate_expressions": "aggregations and expression constructors",
            "context": "DataContext fields and ExecutionOptions",
            "dataset": "Dataset methods",
            "datasource": "the Datasource and Datasink protocols",
            "expr": "expressions and their namespaces",
            "groupby_iterator": "GroupedData and DataIterator",
            "llm": "LLM processors",
            "preprocessors": "preprocessors",
            "toplevel": "module functions and classes",
        },
        pages=(
            Page(
                "dataset",
                "Ray Data Dataset, grouping, and iteration",
                ("dataset", "groupby_iterator"),
            ),
            Page(
                "expressions",
                "Ray Data expressions and aggregations",
                ("expr", "aggregate_expressions"),
            ),
            Page(
                "io", "Ray Data readers, data sources, and data sinks", ("toplevel", "datasource")
            ),
            Page(
                "udfs-ai-multimodal",
                "Ray Data LLM processors and preprocessors",
                ("llm", "preprocessors"),
            ),
            Page("execution-context", "Ray Data execution context", ("context",)),
        ),
    ),
)

_ESCAPE = re.compile(r"([\\`*_<>\[\]{}|$&~^])")


def _prose(text: str) -> str:
    """Escape registry text for a Markdown table cell, keeping its code spans intact."""
    text = " ".join(text.split())
    parts = text.split("`")
    if len(parts) % 2 == 0:  # an unbalanced backtick: treat the whole text as prose
        return _ESCAPE.sub(r"\\\1", text)
    return "".join(
        _ESCAPE.sub(r"\\\1", part) if i % 2 == 0 else "`" + part.replace("|", r"\|") + "`"
        for i, part in enumerate(parts)
    )


def _code(text: str) -> str:
    return "`" + text.replace("|", r"\|") + "`"


def _sentence(text: str) -> str:
    text = text.strip()
    return text if text.endswith((".", "?", "!")) else text + "."


def _spelling(targets: tuple[str, ...]) -> str:
    """The Batcher column, as plain code spans.

    Used where the text is a sort key or a dictionary key rather than something rendered;
    `_spelling_linked` is what a table cell gets.
    """

    def one(target: str) -> str:
        if target.startswith("op:"):
            return f"{_code(OPERATORS.get(target[3:], target[3:]))} operator"
        return _code(target)

    return " + ".join(one(t) for t in targets) if targets else "n/a"


def _spelling_linked(targets: tuple[str, ...]) -> str:
    """The Batcher column, cross-referenced to the reference page for each name.

    A migration table is the one page a reader arrives at knowing the *other* engine's
    name, so the Batcher cell is the only thing on the row they need to look up, and it
    was the one thing that wasn't clickable. `doc_api_links.link` falls back to a plain
    code span for a spelling no reference page publishes, which covers the operator rows
    and the names that are still a gap, so no cell here can become a dead reference.
    """

    def one(target: str) -> str:
        if target.startswith("op:"):
            return f"{_code(OPERATORS.get(target[3:], target[3:]))} operator"
        return _link(target)

    return " + ".join(one(t) for t in targets) if targets else "n/a"


def _link(spelling: str) -> str:
    """`spelling` as a cross-reference, with the pipe escaped for a Markdown table cell."""
    markup = doc_api_links.link(spelling)
    return markup.replace("|", r"\|")


def _notes(row: Mapping) -> str:
    parts: list[str] = []
    if row.need:
        lead = "Not yet" if row.status is Status.GAP else "Missing"
        parts.append(f"{lead}: {_prose(_sentence(row.need))}")
    if row.note:
        lead = "Differs: " if row.status is Status.MISMATCH else ""
        parts.append(f"{lead}{_prose(_sentence(row.note))}")
    if row.reason:
        parts.append(f"Declined: {_prose(_sentence(row.reason))}")
    if row.wave:
        parts.append(f"Wave {row.wave}.")
    return " ".join(parts)


def _implemented() -> set[tuple[str, str]]:
    """The codemod directions `python -m batcher.migrate` runs, read from its source."""
    for node in ast.parse(_CLI.read_text()).body:
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "_IMPLEMENTED" for t in node.targets
        ):
            return _directions(node.value)
    raise SystemExit(f"{_CLI}: no `_IMPLEMENTED` assignment to read the directions from")


def _directions(node: ast.expr) -> set[tuple[str, str]]:
    """Read the `_IMPLEMENTED` set: literal pairs, and `*((engine, "x") for engine in ENGINES)`.

    Only those two shapes are understood, so a new spelling of the set fails loudly here
    instead of the pages silently listing the wrong directions.
    """
    if not isinstance(node, ast.Set):
        raise SystemExit(f"{_CLI}: `_IMPLEMENTED` is not a set display")
    out: set[tuple[str, str]] = set()
    for elt in node.elts:
        if isinstance(elt, ast.Starred) and isinstance(elt.value, ast.GeneratorExp):
            gen = elt.value
            loop = gen.generators[0]
            if not (
                len(gen.generators) == 1
                and isinstance(loop.target, ast.Name)
                and isinstance(loop.iter, ast.Name)
                and loop.iter.id == "ENGINES"
                and isinstance(gen.elt, ast.Tuple)
            ):
                raise SystemExit(f"{_CLI}: unrecognized generator in `_IMPLEMENTED`")
            var = loop.target.id
            for engine in ENGINE_KEYS:
                pair = tuple(
                    engine if isinstance(p, ast.Name) and p.id == var else ast.literal_eval(p)
                    for p in gen.elt.elts
                )
                out.add(pair)  # type: ignore[arg-type]
        else:
            out.add(tuple(ast.literal_eval(elt)))  # type: ignore[arg-type]
    return out


def _surface_kinds() -> dict[tuple[str, str], tuple[str, str]]:
    """`(engine, surface) -> (dotted target, kind)` from the snapshot tool's surface list."""
    tree = ast.parse(_SURFACES.read_text())
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "SURFACES":
            spec = ast.literal_eval(node.value)  # type: ignore[arg-type]
            return {(e, s): (t, k) for e, rows in spec.items() for s, t, k in rows}
    raise SystemExit(f"{_SURFACES}: no `SURFACES` table")


def _version(engine: Engine) -> str:
    return str(json.loads((_SNAPSHOTS / f"{engine.key}.json").read_text())["version"])


def _file_sections(engine: Engine) -> dict[str, list[str]]:
    """Registry file stem -> the surfaces it holds, in file order."""
    return {
        path.stem: list(tomllib.loads(path.read_text()))
        for path in sorted((DATA_DIR / engine.key).glob("*.toml"))
    }


def _direction(source: str, target: str, implemented: set[tuple[str, str]]) -> str:
    if (source, target) in implemented:
        return (
            "This direction is implemented. Without `--write` the command prints a diff and "
            "changes nothing, and `--write` applies it."
        )
    done = ", ".join(f"`--from {s} --to {t}`" for s, t in sorted(implemented))
    return (
        "This direction isn't implemented yet, so the command refuses it with a `ConfigError`. "
        f"The implemented directions are {done}. Until yours lands, port by hand with the "
        "tables on these pages."
    )


class _Renderer:
    """Renders one engine's directory of pages."""

    def __init__(self, engine: Engine, implemented: set[tuple[str, str]]) -> None:
        self.engine = engine
        self.implemented = implemented
        self.kinds = _surface_kinds()
        self.files = _file_sections(engine)
        self.rows = {(r.surface, r.name): r for r in load_registry().for_engine(engine.key)}
        spread = Counter(s for surfaces in self.files.values() for s in surfaces)
        self.shared = {s for s, n in spread.items() if n > 1}
        self.by_file = {
            stem: {s: self._rows(stem, s) for s in surfaces}
            for stem, surfaces in self.files.items()
        }

    def _rows(self, stem: str, surface: str) -> list[Mapping]:
        path = DATA_DIR / self.engine.key / f"{stem}.toml"
        names = tomllib.loads(path.read_text())[surface]
        rows = [self.rows[(surface, name)] for name in names]
        return sorted(rows, key=lambda r: (r.name.lower(), r.name))

    def _label(self, surface: str) -> str:
        target, kind = self.kinds.get((self.engine.key, surface), (surface, "class"))
        if kind in ("all", "public"):
            return f"the `{target}` module"
        if kind == "fields":
            return f"`{surface}` fields"
        return f"`{surface}`"

    def _heading(self, stem: str, surface: str) -> str:
        label = self._label(surface)
        heading = label[0].upper() + label[1:]
        if surface in self.shared:
            heading += f": {self.engine.families[stem]}"
        return heading

    def _codemod(self, source: str, target: str) -> list[str]:
        return [
            "```bash",
            f"python -m batcher.migrate --from {source} --to {target} <paths>",
            "```",
            "",
            "Replace `<paths>` with the files or directories to rewrite. "
            + _direction(source, target, self.implemented),
            "",
        ]

    def _page(self, page: Page) -> str:
        e = self.engine
        lines = [
            _HEADER.format(engine=e.key),
            "",
            f"# {page.title}",
            "",
            f"This page maps {len(self._page_rows(page))} {e.label} names onto their Batcher "
            "spellings, grouped by the class or module they live on. Each row reads in both "
            "directions. {doc}`index` explains the statuses and the waves.",
            "",
            f"To rewrite {e.label} code onto these spellings, run the codemod:",
            "",
            *self._codemod(e.key, "batcher"),
        ]
        for stem in page.files:
            for surface, rows in self.by_file[stem].items():
                lines += [
                    f"## {self._heading(stem, surface)}",
                    "",
                    f"The following table maps the {len(rows)} names on "
                    f"{self._label(surface)}, sorted alphabetically.",
                    "",
                    f"| {e.label} | Batcher | Status | Notes |",
                    "|---|---|---|---|",
                    *(
                        f"| {_code(r.name)} | {_spelling_linked(r.batcher)} | "
                        f"{_STATUS_LABEL[r.status]} | {_notes(r)} |"
                        for r in rows
                    ),
                    "",
                ]
        lines += self._see_also(leaving=False)
        return "\n".join(lines).rstrip() + "\n"

    def _see_also(self, *, leaving: bool) -> list[str]:
        """The closing links every generated page carries.

        A lookup table is where a reader lands from a search, so it is the page most likely
        to be someone's first, and it was the one shape on the site that ended with nothing
        after it. These are the four hops that follow from "I found my name in the table".
        """
        e = self.engine
        rows = [
            "",
            "## See also",
            "",
            f"- {{doc}}`index`: the statuses, the waves, and the other {e.label} pages.",
        ]
        if leaving:
            rows.append(
                f"- {{doc}}`/getting-started/migration/index`: porting the other way, "
                f"from {e.label} onto Batcher."
            )
        else:
            rows.append(
                "- {doc}`leaving-batcher`: the rows that agree, read the other way, "
                "for code moving off Batcher."
            )
        rows += [
            "- {doc}`/getting-started/migration/differences`: what Batcher leaves out on "
            "purpose, and how to prove a port returns the same rows.",
            "- {doc}`/api/reference`: every Batcher spelling in one lookup table.",
            "",
        ]
        return rows

    def _page_rows(self, page: Page) -> list[Mapping]:
        return [r for stem in page.files for rows in self.by_file[stem].values() for r in rows]

    def _index(self) -> str:
        e = self.engine
        every = [r for p in e.pages for r in self._page_rows(p)]
        lines = [
            _HEADER.format(engine=e.key),
            "",
            f"# {e.label} to Batcher",
            "",
            f"This section maps every public name in {e.label} {_version(e)} onto its Batcher "
            "spelling, one page per family of names, and maps the shared spellings back again "
            f"for code leaving Batcher. It covers {len(every)} names.",
            "",
            "The pages are generated from the migration registry in "
            f"`python/batcher/_internal/migration/data/{e.key}/`, which classifies each name in "
            f"the {e.label} surface snapshot exactly once. The `AttributeError` you get when you "
            f"type a {e.label} name on a Batcher object reads the same rows, so the message and "
            "these tables agree.",
            "",
            "## Rewrite code with the codemod",
            "",
            f"The codemod rewrites {e.label} calls onto Batcher spellings:",
            "",
            *self._codemod(e.key, "batcher"),
            "## How to read the tables",
            "",
            f"Every row names the {e.label} spelling, the Batcher spelling, a status, and notes. "
            "The status is the part to read first, because a matching name is not a matching "
            "result. The following table defines each status:",
            "",
            "| Status | Meaning |",
            "|---|---|",
            *(f"| {_STATUS_LABEL[s]} | {m} |" for s, m in _STATUS_MEANING.items()),
            "",
            "A Batcher spelling is a dotted path from the object you call it on: `Dataset` is a "
            "dataset, `Expr` an expression, `GroupBy` the result of `group_by`, and `bt` the "
            "`batcher` package. Spellings joined by `+` are used together.",
            "",
            *self._waves(every),
            "## Pages",
            "",
            "The following table lists the pages in this section with the number of names each "
            "one covers, by status:",
            "",
            "| Page | Names | Canonical or alias | Param | Mismatch | Gap | Out of scope |",
            "|---|---|---|---|---|---|---|",
            *(self._count_row(p) for p in e.pages),
            "",
            "{doc}`leaving-batcher` maps the other way, from Batcher spellings back to "
            f"{e.label}.",
            "",
            "## See also",
            "",
            "- {doc}`../differences`: the concepts that change in any port, such as laziness "
            "and write-mode defaults.",
            "- {doc}`../index`: the migration guide, with the other source engines.",
            "",
            "```{toctree}",
            ":hidden:",
            "",
            *(p.slug for p in e.pages),
            "leaving-batcher",
            "```",
        ]
        return "\n".join(lines) + "\n"

    def _waves(self, every: list[Mapping]) -> list[str]:
        waves = Counter(r.wave for r in every if r.wave)
        return [
            "## Waves",
            "",
            "A row that isn't at parity carries a *wave*: the planned unit of work that closes "
            "it. Waves are an order of work, not release dates. Silent mismatches come first, "
            "because they return different answers without an error. Cheap surface wiring comes "
            "next, then new kernels, then the large families. A row's status changes in the same "
            "commit that closes it, so these pages track progress when they're regenerated.",
            "",
            f"The following table lists the waves that hold {self.engine.label} rows, in "
            "delivery order:",
            "",
            "| Wave | Scope | Rows |",
            "|---|---|---|",
            *(f"| {w} | {_WAVES[w]} | {waves[w]} |" for w in _WAVES if waves[w]),
            "",
        ]

    def _count_row(self, page: Page) -> str:
        c = Counter(r.status for r in self._page_rows(page))
        same = c[Status.CANONICAL]
        return (
            f"| {{doc}}`{page.slug}` | {c.total()} | {same} | {c[Status.PARAM]} | "
            f"{c[Status.MISMATCH]} | {c[Status.GAP]} | {c[Status.OUT_OF_SCOPE]} |"
        )

    def _leaving(self) -> str:
        e = self.engine
        # Keyed by the raw spelling tuple rather than its rendered text, because the cell
        # is now a cross-reference: sorting or grouping on the markup would order the
        # table by the role name every row shares.
        back: dict[tuple[str, ...], list[str]] = {}
        for page in e.pages:
            for r in self._page_rows(page):
                if r.status is Status.CANONICAL and r.batcher:
                    back.setdefault(r.batcher, []).append(_code(f"{r.surface}.{r.name}"))
        lines = [
            _HEADER.format(engine=e.key),
            "",
            f"# Leaving Batcher for {e.label}",
            "",
            f"This page maps Batcher spellings back to {e.label}, for code moving the other way. "
            f"It lists only the rows whose status is canonical or alias, where both engines "
            f"compute the same thing. A Batcher spelling that behaves differently in {e.label} "
            "isn't listed here, so look it up on the forward pages in {doc}`index` before "
            "porting it.",
            "",
            "To rewrite Batcher code the other way, run the codemod in reverse:",
            "",
            *self._codemod("batcher", e.key),
            "## Batcher to " + e.label,
            "",
            f"The following table maps {len(back)} Batcher spellings to the {e.label} names that "
            f"compute the same thing, sorted by Batcher spelling. Each {e.label} name is prefixed "
            "with the class or module it lives on.",
            "",
            f"| Batcher | {e.label} |",
            "|---|---|",
            *(
                f"| {_spelling_linked(targets)} | {', '.join(sorted(set(names)))} |"
                for targets, names in sorted(back.items(), key=lambda kv: _spelling(kv[0]).lower())
            ),
            *self._see_also(leaving=True),
        ]
        return "\n".join(lines).rstrip() + "\n"

    def render(self) -> dict[Path, str]:
        out = MIGRATION_DOCS / self.engine.directory
        pages = {out / f"{p.slug}.md": self._page(p) for p in self.engine.pages}
        pages[out / "index.md"] = self._index()
        pages[out / "leaving-batcher.md"] = self._leaving()
        return pages


def render() -> dict[Path, str]:
    """Render every generated page.

    Returns:
        Each page's path and its full text.

    Raises:
        SystemExit: When a registry file is not assigned to exactly one page.
    """
    implemented = _implemented()
    pages: dict[Path, str] = {}
    for engine in ENGINES:
        renderer = _Renderer(engine, implemented)
        placed = [f for p in engine.pages for f in p.files]
        if sorted(placed) != sorted(renderer.files):
            raise SystemExit(
                f"{engine.key}: registry files {sorted(renderer.files)} must each be on exactly "
                f"one page; the page table places {sorted(placed)}"
            )
        pages.update(renderer.render())
    return pages


def unexpected(pages: dict[Path, str]) -> list[Path]:
    """Files in a generated directory that the generator would not write.

    Args:
        pages: The output of `render`.

    Returns:
        The stale files, sorted.
    """
    dirs = {MIGRATION_DOCS / e.directory for e in ENGINES}
    return sorted(p for d in dirs if d.is_dir() for p in d.iterdir() if p not in pages)


def main() -> int:
    """Write the pages, or verify they are current under `--check`."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if any page is stale")
    args = parser.parse_args()
    pages = render()
    stale = [p for p, text in pages.items() if not p.exists() or p.read_text() != text]
    extra = unexpected(pages)
    if args.check:
        for path in [*stale, *extra]:
            print(f"stale: {path.relative_to(REPO)}", file=sys.stderr)
        if stale or extra:
            print("run `just migration-docs` and commit the result", file=sys.stderr)
            return 1
        return 0
    for path in extra:
        path.unlink()
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(pages[path])
    print(f"{len(pages)} pages, {len(stale)} written, {len(extra)} removed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
