"""Generate typing declarations for the methods Batcher binds onto classes at runtime.

Some public methods are attached with `setattr` after their class is defined rather than
written in its body: the parameterless `.str`/`.dt`/`.list` accessors come from a table
(`plan/expr_ir/namespaces/_bind.py`), `AggExpr` borrows `Expr`'s math methods, and
`CaseBuilder` forwards `Expr`'s operators. They work, and Sphinx documents them, but a type
checker reads source, not the runtime, so to pyright and mypy those names do not exist:
``col("s").str.upper()`` was an unknown attribute and ``when(c).then(1) + 1`` an unsupported
operator.

This writes `python/batcher/plan/expr_ir/declared/bound.py`, one class of declarations per
target, each read from the live runtime: the bound name, its advertised signature, and the
first line of its docstring. Each target class inherits its declarations only under
``TYPE_CHECKING``, so the runtime class is unchanged. A ``.pyi`` stub was the other option,
and the wrong one: a stub beside a ``.py`` replaces the whole module for a checker, so it
would have to restate every hand-written method of these large namespace modules too.

Run: `just gen-decls`. `tests/unit/test_bound_decls.py` fails when the committed file is
stale, and when a public method is bound at runtime onto a class this does not cover.
"""

from __future__ import annotations

import builtins
import importlib
import inspect
import re
import subprocess
import sys
import typing
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT / "python") not in sys.path:
    sys.path.insert(0, str(ROOT / "python"))

TARGET = ROOT / "python" / "batcher" / "plan" / "expr_ir" / "declared" / "bound.py"

#: `(defining module, class, declaration class, signature source)` for every class with
#: runtime-bound methods. The source is the class whose method of the same name supplies the
#: declared signature, when the bound function is a generic forwarder: `CaseBuilder`'s
#: operators take ``*args`` and finish the `Case`, so they mean exactly what `Expr`'s do.
TARGETS = (
    ("batcher.plan.expr_ir.namespaces.strings", "_StrNamespace", "StrBound", None),
    ("batcher.plan.expr_ir.namespaces.temporal", "_DtNamespace", "DtBound", None),
    ("batcher.plan.expr_ir.namespaces.collections", "_ListNamespace", "ListBound", None),
    ("batcher.plan.expr_ir.core", "AggExpr", "AggExprBound", None),
    ("batcher.plan.expr_ir.nodes", "CaseBuilder", "CaseBuilderBound", "Expr"),
)

#: Operators whose `Expr` signature returns an expression where `object`'s returns `bool`.
_OVERRIDES_OBJECT = frozenset({"__eq__", "__ne__"})

#: Modules searched for a name an annotation uses but its function's globals lack (a name
#: imported only under ``TYPE_CHECKING`` where the function was defined).
_FALLBACK_MODULES = (
    "batcher.plan.expr_ir.core",
    "batcher.plan.expr_ir.nodes",
    "batcher.plan.expr_ir.func_nodes",
)

_HEADER = '''"""Typing declarations for the methods bound onto expression classes at runtime.

GENERATED by `tools/gen_bound_decls.py` from the live classes. Do not edit; run
`just gen-decls`. `tests/unit/test_bound_decls.py` fails when this file is stale.

Each class here declares, for type checkers and editors only, the methods one runtime class
gains through `setattr`. That class inherits these declarations under ``TYPE_CHECKING`` and
`object` otherwise, so nothing here runs or is reachable at runtime.
"""

from __future__ import annotations
'''


class _Text:
    """An annotation rendered verbatim, so `inspect` prints ``Expr`` rather than ``'Expr'``."""

    def __init__(self, text: str) -> None:
        self.text = text

    def __repr__(self) -> str:
        return self.text


def runtime_bound(cls: type) -> list[str]:
    """The names of the functions on `cls` that its class body does not define.

    A function written in the body has a ``co_qualname`` under the class's name; one bound
    later (a table-generated accessor, a method borrowed from another class, a forwarder)
    does not. Decorators are unwrapped first so a ``@contextmanager`` method is not mistaken
    for a bound one.

    Args:
        cls: The class to inspect.

    Returns:
        The bound names, sorted.
    """
    out = []
    for name, obj in vars(cls).items():
        if not inspect.isfunction(obj):
            continue
        code = inspect.unwrap(obj).__code__
        if not code.co_qualname.startswith(f"{cls.__qualname__}."):
            out.append(name)
    return sorted(out)


def _annotation_text(annotation: Any) -> str | None:
    if annotation is inspect.Parameter.empty:
        return None
    if isinstance(annotation, str):
        return annotation
    if inspect.isclass(annotation):
        return annotation.__name__
    raise TypeError(f"cannot render annotation {annotation!r}")


def _import_for(name: str, fn: Any) -> tuple[str, str] | None:
    """`(module, name)` to import so `name` resolves in the declarations, or None for a builtin."""
    if hasattr(builtins, name):
        return None
    found = fn.__globals__.get(name)
    home = fn.__module__
    if found is None:
        for module in _FALLBACK_MODULES:
            found = vars(importlib.import_module(module)).get(name)
            if found is not None:
                home = module
                break
    if found is None:
        raise NameError(f"{fn.__qualname__}: cannot resolve annotation name {name!r}")
    if inspect.isclass(found) or inspect.isfunction(found):
        return found.__module__, name
    if getattr(found, "__module__", None) == "typing" and hasattr(typing, name):
        return "typing", name
    return home, name


def _declaration(name: str, fn: Any, imports: set[tuple[str, str]]) -> str:
    sig = inspect.signature(fn)
    params, texts = [], []
    for i, param in enumerate(sig.parameters.values()):
        # `self` stays bare: the declaration class is not the class the method serves.
        text = None if i == 0 else _annotation_text(param.annotation)
        texts.append(text)
        params.append(param.replace(annotation=_Text(text) if text else inspect.Parameter.empty))
    ret = _annotation_text(sig.return_annotation)
    texts.append(ret)
    rendered = sig.replace(
        parameters=params,
        return_annotation=_Text(ret) if ret else inspect.Signature.empty,
    )
    for text in texts:
        for ident in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", text or ""):
            needed = _import_for(ident, fn)
            if needed:
                imports.add(needed)
    first = (inspect.getdoc(fn) or name).strip().splitlines()[0]
    summary = first.replace("\\", "\\\\").rstrip('"')
    ignore = "  # type: ignore[override]" if name in _OVERRIDES_OBJECT else ""
    return f'    def {name}{rendered}:{ignore}\n        """{summary}"""\n'


def render() -> str:
    """The full, ruff-formatted text of the declarations module.

    Returns:
        The module source.
    """
    imports: set[tuple[str, str]] = set()
    classes = []
    for module, cls_name, decl_name, source in TARGETS:
        mod = importlib.import_module(module)
        cls = getattr(mod, cls_name)
        sig_cls = getattr(mod, source) if source else cls
        body = [_declaration(n, getattr(sig_cls, n), imports) for n in runtime_bound(cls)]
        doc = f'    """The methods `{module}.{cls_name}` gains at runtime."""\n'
        classes.append(f"class {decl_name}:\n{doc}\n" + "\n".join(body))
    lines = [_HEADER, "from typing import TYPE_CHECKING\n", "if TYPE_CHECKING:"]
    by_module: dict[str, list[str]] = {}
    for module, name in sorted(imports):
        by_module.setdefault(module, []).append(name)
    lines += [f"    from {m} import {', '.join(names)}" for m, names in by_module.items()]
    names = ", ".join(f'"{t[2]}"' for t in sorted(TARGETS, key=lambda t: t[2]))
    lines.append(f"\n__all__ = [{names}]\n")
    source = "\n".join(lines) + "\n\n" + "\n\n".join(classes)
    return _ruff(source)


def _ruff(source: str) -> str:
    """Sort imports and format with the repo's ruff settings, so the output is lint-clean."""
    filename = str(TARGET)
    for args in (["check", "--select", "I", "--fix", "--quiet"], ["format", "--quiet"]):
        source = subprocess.run(
            [sys.executable, "-m", "ruff", *args, "--stdin-filename", filename, "-"],
            input=source,
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        ).stdout
    return source


def main() -> None:
    """Write the declarations module."""
    TARGET.write_text(render())
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
