"""Generate `docs/api/return-types.md`, what each public entry point hands back.

A lazy API has one question every caller asks before anything else: does this call give me
another `Dataset` to chain, or does it run the query and hand back a result? The answer is
in each signature's return annotation, so this page is rendered from the live annotations
rather than written by hand. For each receiver it states how many members continue the
chain, then lists every other member, grouped by the type it returns: the terminals, the
aggregates and the writers.

Run: `just return-types-doc`. `tests/docs/test_return_types_fresh.py` fails when the
committed page no longer matches the annotations.
"""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
for _path in (ROOT, ROOT / "python"):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))

TARGET = ROOT / "docs" / "api" / "return-types.md"

#: `(receiver spelling, heading, the category that continues its chain)`, in page order.
#: The receiver spellings are `tools.parity.batcher_targets.receivers()` keys.
SECTIONS = (
    ("Dataset", "Dataset", "Dataset"),
    ("GroupBy", "GroupBy", "Dataset"),
    ("Dataset.write", "Dataset.write", None),
    ("Dataset.ml", "Dataset.ml", "Dataset"),
    ("Dataset.dq", "Dataset.dq", "DatasetDQ"),
    ("bt.read", "bt.read", "Dataset"),
    ("bt", "Top-level functions (bt)", "Expr"),
    ("Expr", "Expr", "Expr"),
    ("AggExpr", "AggExpr", "Expr"),
    ("Session", "Session", None),
    ("StreamingQuery", "StreamingQuery", None),
)

_SCALARS = {"int", "float", "bool", "str", "bytes", "None"}

_HEADER = """\
<!-- GENERATED by tools/gen_return_types_doc.py from the live return annotations. Do not
edit; run `just return-types-doc`. tests/docs/test_return_types_fresh.py gates the drift. -->

# Return types

This page lists what each public entry point returns, read from the signatures themselves.
Batcher is lazy, so the first thing to know about a call is whether it continues the chain
or ends it. A call that returns a `Dataset`, `GroupBy`, or `Expr` only describes more work.
A call that returns anything else runs the query, or a part of it, and hands back a result.

Each section below names how many members continue that receiver's chain, then lists every
other member, grouped by the type it returns. The *category* column sorts those types into
the families that matter when you read a pipeline:

| Category | Meaning |
| --- | --- |
| Dataset | A new lazy `Dataset`. Nothing has run. |
| Expr | A lazy column expression, including its node subclasses such as `MathExpr`. |
| AggExpr | An aggregate, valid inside `group_by().agg(...)`, `agg(...)`, or `.over(...)`. |
| AggExpr or Expr | An aggregate that becomes a plain expression in a non-aggregating context. |
| pa.Table | The whole result, materialized as an Arrow table. |
| scalar | A single Python value. `Any` marks a reduction whose type follows the column's. |
| iterator | A lazy stream: batches or rows arrive as you consume them. |
| collection | A `list`, `tuple`, or `dict` of the named type. |
| WriteManifest | The record of a finished batch write. |
| StreamingQuery | A handle to a running streaming query. |
| accessor | A typed namespace such as `.str` or `.dt`, whose methods build expressions. |
| nothing | `None`. The call is run for its side effect. |

Any other category is a type from another library, such as `pd.DataFrame`, or a Batcher
handle named after its class.
"""


def _members(receiver: Any) -> dict[str, str]:
    """Public callable members and properties of `receiver` -> their return annotation text."""
    out: dict[str, str] = {}
    names = getattr(receiver, "__all__", None) or dir(receiver)
    for name in names:
        if name.startswith("_"):
            continue
        attr = (
            inspect.getattr_static(receiver, name)
            if inspect.isclass(receiver)
            else getattr(receiver, name)
        )
        fn = attr.fget if isinstance(attr, property) else attr
        if isinstance(fn, (staticmethod, classmethod)):
            fn = fn.__func__
        if inspect.isclass(fn) or not callable(fn):
            continue
        try:
            raw = inspect.signature(fn).return_annotation
        except (TypeError, ValueError):
            continue
        out[name] = _text(raw)
    return out


def _text(raw: Any) -> str:
    if raw is inspect.Signature.empty:
        return "(unannotated)"
    if isinstance(raw, str):
        return raw
    if inspect.isclass(raw):
        return raw.__name__
    return str(raw).replace("typing.", "")


def _expr_class(name: str) -> str | None:
    """`"AggExpr"` / `"Expr"` when `name` is that class or an `Expr` subclass, else None."""
    import batcher.plan.expr_ir as expr_ir
    from batcher.plan.expr_ir import core, func_nodes, nodes

    if name == "AggExpr":
        return "AggExpr"
    for module in (expr_ir, core, nodes, func_nodes):
        found = getattr(module, name, None)
        if inspect.isclass(found) and issubclass(found, core.Expr):
            return "Expr"
    return None


def _split_union(text: str) -> list[str]:
    """The top-level ``|`` alternatives of `text`, leaving a ``|`` inside brackets alone."""
    parts, depth, current = [], 0, ""
    for ch in text:
        depth += ch == "["
        depth -= ch == "]"
        if ch == "|" and depth == 0:
            parts.append(current.strip())
            current = ""
        else:
            current += ch
    return [*parts, current.strip()]


def _one(text: str) -> str:
    if text == "None":
        return "nothing"
    if text == "Any" or text in _SCALARS:
        return "scalar"
    if re.match(r"(Iterator|Iterable|Generator|AsyncIterator)\[", text):
        return "iterator"
    if re.match(r"(list|tuple|dict|set)\b", text):
        return "collection"
    if re.fullmatch(r"_[A-Za-z]+Namespace", text):
        return "accessor"
    return _expr_class(text) or text


def category(text: str) -> str:
    """The reader-facing family a return annotation belongs to.

    A union names each family it can return, so ``WriteManifest | StreamingQuery`` reads as
    both; an optional ``None`` beside other alternatives is dropped, as a scalar that may be
    missing is still a scalar.

    Args:
        text: The annotation as written.

    Returns:
        One of the categories the page's legend defines, or the type itself.
    """
    parts = _split_union(text)
    if len(parts) > 1:
        parts = [p for p in parts if p != "None"]
    kinds = list(dict.fromkeys(_one(p) for p in parts))
    return " or ".join(sorted(kinds)) if {"AggExpr", "Expr"} >= set(kinds) else " or ".join(kinds)


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _section(heading: str, members: dict[str, str], chain: str | None) -> list[str]:
    groups: dict[str, list[str]] = {}
    for name, text in members.items():
        groups.setdefault(text, []).append(name)
    chained = sorted(n for n, t in members.items() if chain and category(t) == chain)
    rows = [
        (category(text), text, sorted(names))
        for text, names in groups.items()
        if not (chain and category(text) == chain)
    ]
    others = sum(len(names) for _, _, names in rows)
    out = [f"## {heading}", ""]
    if not rows:
        return [*out, f"All {len(chained)} public members return {_article(chain)} `{chain}`.", ""]
    if chained:
        out.append(
            f"{len(chained)} public members continue the chain and return "
            f"{_article(chain)} `{chain}`. The other {others} are listed below."
        )
    else:
        out.append(f"All {others} public members are listed below.")
    out += ["", "| Category | Returns | Members |", "| --- | --- | --- |"]
    for cat, text, names in sorted(rows, key=lambda r: (r[0].lower(), r[1])):
        listed = ", ".join(f"`{n}`" for n in names)
        out.append(f"| {_cell(cat)} | `{_cell(text)}` | {listed} |")
    out.append("")
    return out


def _article(word: str | None) -> str:
    return "an" if word and word[0] in "AEIOU" else "a"


def render() -> str:
    """The full text of `docs/api/return-types.md`.

    Returns:
        The page source.
    """
    from tools.parity.batcher_targets import receivers

    found = receivers()
    lines = [_HEADER]
    for key, heading, chain in SECTIONS:
        lines += _section(heading, _members(found[key]), chain)
    lines += [
        "## See also",
        "",
        "- {doc}`/api/reference`: the everyday calls, one lookup table.",
        "- {doc}`/api/symbols/index`: every signature in full.",
        "- {doc}`/user-guide/index`: when to end a chain, and with which terminal.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    """Write the page."""
    TARGET.write_text(render())
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
