"""The committed baseline of Batcher's public names, and the ratchet that keeps it honest.

`tools/public_surface.py` says what is public today. Nothing said what was public
yesterday, so a released name could disappear in a refactor with every gate green: the
coverage tests only check that today's names are documented, and a vanished name owes no
documentation. `public_surface_baseline.txt` records every public spelling, and
`tests/unit/test_public_surface_ratchet.py` fails when one of them stops resolving unless
its removal is recorded in `_internal/migration/data/renames.toml`, the registry the
`batcher.migrate` codemod and the migration-error guidance already read. A removal is
therefore always a migration, never an accident.

A name is spelled the way a user reaches it, not by the module that defines it, so moving
a class between modules is not a removal: ``Dataset.filter``, ``Expr.str.upper`` and
``bt.col`` for the receivers in `tools.parity.batcher_targets`, the import path for a
subpackage export (``batcher.ml.Pipeline``), and the bare class name for an accessor class
reached only through an attribute (``SchemaMeta.columns``).

Run: `just surface-baseline` after adding public names. The write never drops a name that
vanished without a recorded rename, so regenerating cannot launder a removal.
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
for _path in (ROOT, ROOT / "python"):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))

BASELINE = ROOT / "tools" / "public_surface_baseline.txt"

_HEADER = """\
# Every public spelling, as a user reaches it. GENERATED by
# tools/public_surface_baseline.py; run `just surface-baseline`. A line may be removed
# only by recording the removal in _internal/migration/data/renames.toml
# (tests/unit/test_public_surface_ratchet.py).
"""


def _entry_spelling(qual: str, public_modules: set[str]) -> str:
    """How a user names a public function or class reached as `qual`."""
    module, _, name = qual.rpartition(".")
    if module == "batcher":
        return f"bt.{name}"
    if module in public_modules:
        return qual
    return name


def spellings() -> set[str]:
    """Every public name today, spelled as a user reaches it.

    Returns:
        The spellings, from `tools.public_surface.public_callables`.
    """
    from tools.parity.batcher_targets import receivers
    from tools.public_surface import _SUBPACKAGES, public_callables, public_classes

    public_modules = {*_SUBPACKAGES, "batcher.ml.preprocessors"}
    by_class: dict[int, str] = {
        id(obj): key for key, obj in receivers().items() if inspect.isclass(obj)
    }
    classes: dict[str, Any] = dict(public_classes())
    out: set[str] = set()
    for qual, _ in public_callables():
        if qual in classes:
            out.add(_entry_spelling(qual, public_modules))
            continue
        owner, _, member = qual.rpartition(".")
        if owner not in classes:
            out.add(_entry_spelling(qual, public_modules))
            continue
        receiver = by_class.get(id(classes[owner])) or _entry_spelling(owner, public_modules)
        out.add(f"{receiver}.{member}")
    return out


def recorded_removals() -> set[str]:
    """Every spelling `renames.toml` records as removed, as ``<receiver>.<name>``.

    A rename on the ``bt`` receiver covers both the module function (``bt.name``) and, for a
    class, its root export, which spell the same way.

    Returns:
        The recorded removals.
    """
    from batcher._internal.migration.renames import load_renames

    return {f"{receiver}.{name}" for receiver, rules in load_renames().items() for name in rules}


def read_baseline() -> set[str]:
    """The committed baseline.

    Returns:
        Its spellings, comments and blank lines dropped.
    """
    lines = BASELINE.read_text().splitlines() if BASELINE.exists() else []
    return {ln.strip() for ln in lines if ln.strip() and not ln.startswith("#")}


def next_baseline() -> set[str]:
    """What `--write` records: today's names, plus every vanished name not recorded as removed.

    Keeping an unrecorded removal in the baseline is what makes regeneration safe: the
    ratchet test still fails on it until the removal is recorded in `renames.toml`.

    Returns:
        The baseline to write.
    """
    current = spellings()
    vanished = read_baseline() - current
    return current | (vanished - recorded_removals())


def main() -> None:
    """Write the baseline."""
    names = sorted(next_baseline())
    BASELINE.write_text(_HEADER + "".join(f"{n}\n" for n in names))
    print(f"wrote {len(names)} public names to {BASELINE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
