"""Vendor the Join Order Benchmark's 113 queries into the benchmark suite, once.

JOB (Leis et al., *How Good Are Query Optimizers, Really?*) is the standard test of **join
ordering**: 113 queries over the real IMDb database, with 3-16 joins each and correlations
between predicates that defeat the independence assumptions a textbook cost model makes.
That makes it the workload Batcher's adaptive re-optimization is aimed squarely at, which is
why it is worth carrying despite being the one benchmark here that needs a bulk download.

The queries are copied verbatim from the reference implementation
(`github.com/gregrahn/join-order-benchmark`) into
`benchmarks/suites/standard/job_queries.sql`, with a `-- @query <name>` delimiter before
each, the same way `vendor_tpcds_queries.py` handles TPC-DS. Re-run only to refresh; the
output is committed.

Usage:
    python tools/vendor_job_queries.py
"""

from __future__ import annotations

import argparse
import json
import os
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(REPO, "benchmarks", "suites", "standard", "job_queries.sql")

CONTENTS_API = "https://api.github.com/repos/gregrahn/join-order-benchmark/contents/"
RAW_BASE = "https://raw.githubusercontent.com/gregrahn/join-order-benchmark/master/"

HEADER = """\
-- Join Order Benchmark (JOB) -- 113 queries over the real IMDb database.
--
-- GENERATED by tools/vendor_job_queries.py -- do not edit by hand.
--
-- Source: github.com/gregrahn/join-order-benchmark, the reference implementation for
-- Leis et al., "How Good Are Query Optimizers, Really?" (VLDB 2015). The queries are
-- copied verbatim; the data is the IMDb snapshot that paper used, which
-- `benchmarks/sources/tables.py` fetches and converts to parquet.
--
-- Each query is preceded by a `-- @query <name>` line, which is how
-- `benchmarks/suites/standard/job.py` splits this file.
"""


def _query_names() -> list[str]:
    """The 113 query file names, from the repository listing (`1a.sql` ... `33c.sql`)."""
    with urllib.request.urlopen(CONTENTS_API, timeout=60) as fh:
        listing = json.load(fh)
    names = [f["name"] for f in listing if f["name"].endswith(".sql") and f["name"][0].isdigit()]
    return sorted(names, key=lambda n: (int("".join(c for c in n if c.isdigit())), n))


def _fetch(name: str) -> str:
    with urllib.request.urlopen(RAW_BASE + name, timeout=60) as fh:
        return fh.read().decode()


def vendor(out_path: str) -> int:
    """Write every JOB query to ``out_path``. Returns the number written."""
    names = _query_names()
    if len(names) != 113:
        raise RuntimeError(f"expected 113 JOB queries in the repository, found {len(names)}")
    parts = [HEADER]
    for name in names:
        sql = _fetch(name).strip().rstrip(";").strip()
        parts.append(f"\n-- @query job-q{name[:-4]}\n{sql}\n")
    with open(out_path, "w") as fh:
        fh.write("".join(parts))
    return len(names)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=DEFAULT_OUT, help="destination .sql file")
    args = parser.parse_args()
    print(f"wrote {vendor(args.out)} JOB queries to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
