"""Vendor the official TPC-DS query set into the benchmark suite, once.

The benchmark suite registers its queries offline, at import time, so the 99 TPC-DS
statements have to live in the tree rather than be fetched per run. They are not written
by hand: DuckDB's ``tpcds`` extension ships the benchmark's own query text (the same
extension whose ``dsdgen`` this suite already uses to materialize the tables), and this
script copies it verbatim into ``benchmarks/suites/standard/tpcds_queries.sql`` with a
``-- @query qN`` delimiter before each one.

Re-run it only to refresh against a newer DuckDB; the output is committed.

Usage:
    python tools/vendor_tpcds_queries.py
"""

from __future__ import annotations

import argparse
import os

import duckdb

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(REPO, "benchmarks", "suites", "standard", "tpcds_queries.sql")

HEADER = """\
-- TPC-DS: the official 99-query decision-support benchmark.
--
-- GENERATED by tools/vendor_tpcds_queries.py -- do not edit by hand.
--
-- Source: DuckDB's `tpcds` extension (`SELECT query_nr, query FROM tpcds_queries()`),
-- which ships the benchmark's own query text alongside the `dsdgen` generator that
-- `benchmarks/sources/tables.py` uses to materialize the tables. Vendored here because
-- the suite registers its cases offline at import time, and because a hand-typed
-- benchmark query is a fabricated benchmark query.
--
-- Vendored from duckdb {version}.
--
-- Each query is preceded by a `-- @query <name>` line, which is how
-- `benchmarks/suites/standard/tpcds.py` splits this file.
"""


def vendor(out_path: str) -> int:
    """Write every TPC-DS query from the DuckDB extension to ``out_path``."""
    con = duckdb.connect()
    con.sql("INSTALL tpcds; LOAD tpcds;")
    rows = con.sql("SELECT query_nr, query FROM tpcds_queries() ORDER BY query_nr").fetchall()
    parts = [HEADER.format(version=duckdb.__version__)]
    for number, query in rows:
        parts.append(f"\n-- @query tpcds-q{number}\n{query.strip()}\n")
    with open(out_path, "w") as fh:
        fh.write("".join(parts))
    return len(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=DEFAULT_OUT, help="destination .sql file")
    args = parser.parse_args()
    count = vendor(args.out)
    print(f"wrote {count} TPC-DS queries to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
