"""Every PySpark, Polars, Daft and Ray Data name is classified once, and correctly.

"Full parity" is only a claim somebody can check if it has a denominator. That denominator is
the committed surface snapshot (`tools/parity/surfaces/<engine>.json`, regenerated by
`just parity-snapshot`), and the registry (`batcher._internal.migration`) must say something
about every name in it. These tests hold four lines:

* **Completeness.** A snapshot name with no row fails, so upgrading a competitor cannot quietly
  add surface nobody has looked at. A row with no snapshot name fails too, because a mapping
  for a name the competitor does not have is a mapping nobody will ever need.
* **Targets resolve.** A row that points at a Batcher spelling points at something that exists.
* **One spelling.** A competitor's own spelling that also resolves on the Batcher receiver the
  user would type it on is a second spelling of that capability. The row must say so
  (`alias`), which is what the alias-removal work drains to zero, or the two names must mean
  different things (`mismatch`).
* **Declines only shrink.** The out-of-scope count per engine is held to a recorded budget.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from tools.parity.batcher_targets import SURFACE_RECEIVERS, resolve

from batcher._internal.migration import ENGINES, Mapping, Status, load_registry

ROOT = Path(__file__).resolve().parents[2]
SNAPSHOTS = ROOT / "tools" / "parity" / "surfaces"
BUDGET = json.loads((ROOT / "tools" / "parity" / "out_of_scope_budget.json").read_text())


def _snapshot(engine: str) -> dict[str, list[str]]:
    return json.loads((SNAPSHOTS / f"{engine}.json").read_text())["surfaces"]


@pytest.fixture(scope="module")
def registry():
    return load_registry()


def test_every_engine_has_a_snapshot_and_rows(registry) -> None:
    # Positive control for everything below: an empty snapshot or an empty registry would make
    # each completeness check pass vacuously.
    for engine in ENGINES:
        names = sum(len(v) for v in _snapshot(engine).values())
        rows = sum(1 for _ in registry.for_engine(engine))
        assert names > 400, f"{engine} snapshot holds only {names} names"
        assert rows >= names, f"{engine}: {rows} rows for {names} snapshot names"


@pytest.mark.parametrize("engine", ENGINES)
def test_every_snapshot_name_is_classified(registry, engine: str) -> None:
    missing = [
        f"{surface}.{name}"
        for surface, names in _snapshot(engine).items()
        for name in names
        if registry.get(engine, surface, name) is None
    ]
    assert not missing, f"{len(missing)} unclassified {engine} names, e.g. {missing[:15]}"


@pytest.mark.parametrize("engine", ENGINES)
def test_every_row_names_a_real_competitor_spelling(registry, engine: str) -> None:
    snap = {(s, n) for s, names in _snapshot(engine).items() for n in names}
    stray = [
        f"{r.surface}.{r.name}"
        for r in registry.for_engine(engine)
        if (r.surface, r.name) not in snap
    ]
    assert not stray, f"{len(stray)} {engine} rows for names the snapshot lacks, e.g. {stray[:15]}"


@pytest.mark.parametrize("engine", ENGINES)
def test_every_batcher_target_resolves(registry, engine: str) -> None:
    bad = [
        f"{r.surface}.{r.name} -> {t}"
        for r in registry.for_engine(engine)
        for t in r.batcher
        if resolve(t) is None
    ]
    assert not bad, f"{len(bad)} {engine} targets do not resolve, e.g. {bad[:15]}"


def test_no_row_points_at_a_spelling_being_removed(registry) -> None:
    # A mapping to a spelling in `renames.toml` would stop resolving the moment the alias
    # removal deletes it, and would send a migrating user to a name that is on its way out.
    from batcher._internal.migration import load_renames

    renames = load_renames()
    doomed = [
        f"{r.engine}:{r.surface}.{r.name} -> {t}"
        for r in registry.rows.values()
        for t in r.batcher
        if t.rpartition(".")[2] in renames.get(t.rpartition(".")[0], {})
    ]
    assert not doomed, f"{len(doomed)} rows target removed spellings: {doomed}"


def _undeclared_second_spellings(rows) -> list[str]:
    out = []
    for row in rows:
        receiver = SURFACE_RECEIVERS.get((row.engine, row.surface))
        if receiver is None or row.status in (Status.ALIAS, Status.MISMATCH):
            continue
        own = f"{receiver}.{row.name}"
        if resolve(own) is None or own in row.batcher:
            continue
        out.append(f"{row.surface}.{row.name} ({row.status.value}) also resolves as {own}")
    return out


@pytest.mark.parametrize("engine", ENGINES)
def test_a_competitor_spelling_on_the_batcher_receiver_is_declared(registry, engine: str) -> None:
    undeclared = _undeclared_second_spellings(registry.for_engine(engine))
    assert not undeclared, (
        f"{len(undeclared)} second spellings not declared, e.g. {undeclared[:15]}"
    )


def test_the_second_spelling_check_can_fail() -> None:
    # Negative control: `sort` is a real `Dataset` method, so a row claiming a competitor's
    # `sort` is spelled `limit` here would be a second spelling, and the check must reject it.
    # Declared as a `mismatch` (the same word, a different meaning), it must accept it.
    planted = Mapping("ray_data", "Dataset", "sort", Status.CANONICAL, ("Dataset.limit",))
    assert _undeclared_second_spellings([planted])
    declared = Mapping("ray_data", "Dataset", "sort", Status.MISMATCH, ("Dataset.limit",))
    assert not _undeclared_second_spellings([declared])


@pytest.mark.parametrize("engine", ENGINES)
def test_out_of_scope_stays_within_budget(registry, engine: str) -> None:
    declined = sum(1 for r in registry.for_engine(engine) if r.status is Status.OUT_OF_SCOPE)
    assert declined <= BUDGET[engine], (
        f"{engine} declines {declined} names against a budget of {BUDGET[engine]}; "
        "the budget may shrink, never grow"
    )
