"""Generate what each Batcher method returns, as receivers the `batcher.migrate` codemod can follow.

The codemod rewrites `ds.groupby(...)` to `ds.group_by(...)` and must never rewrite
`pandas_df.groupby(...)`, which is spelled identically and sits in the same test files. It
tells the two apart by following receivers: `bt.from_pydict(...)` is a `Dataset`, `.filter()`
on a `Dataset` is a `Dataset`, `.str` on an `Expr` is `Expr.str`. The codemod imports no
engine (it has to run where the engine is not built), so that knowledge is generated here
from the live annotations and committed as `data/returns.toml` beside the registry.
`tests/unit/test_migration_returns_fresh.py` regenerates it in memory and fails on drift.

Only returns that are themselves receivers are recorded; a method returning `int` or
`pa.Table` ends the chain, which is what the codemod should do there too. Expression node
subclasses (`StrFunc`, `MathExpr`, `Cast`) collapse to `Expr`, because every one of them is
typed `Expr` to a user.
"""

from __future__ import annotations

import inspect
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

OUT = ROOT / "python" / "batcher" / "_internal" / "migration" / "data" / "returns.toml"

_HEADER = """\
# GENERATED by tools/parity/gen_migration_returns.py. Do not edit.
#
# For each receiver, the receiver each public method or property returns. The batcher.migrate
# codemod follows these to know which names in a script are Batcher objects, so it rewrites
# `ds.groupby` and leaves `pandas_df.groupby` alone.
"""


def _annotation_class(fn: Any) -> Any:
    raw = inspect.signature(fn).return_annotation
    if inspect.isclass(raw):
        return raw
    if not isinstance(raw, str):
        return None
    text = re.sub(r"\s*\|\s*None\b|\bNone\s*\|\s*", "", raw).strip()
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", text):
        return None
    found = getattr(fn, "__globals__", {}).get(text)
    if found is None:
        # `from __future__ import annotations` + a TYPE_CHECKING import: fall back to the
        # receiver table's own class names.
        from tools.parity.batcher_targets import receivers

        found = next(
            (v for v in receivers().values() if inspect.isclass(v) and v.__name__ == text),
            None,
        )
    return found if inspect.isclass(found) else None


def _receiver_of(cls: Any, by_class: dict[type, str]) -> str | None:
    if cls in by_class:
        return by_class[cls]
    from batcher.plan.expr_ir.core import Expr

    if isinstance(cls, type) and issubclass(cls, Expr):
        return "Expr"
    return None


def generate() -> dict[str, dict[str, str]]:
    """Walk every class receiver and `bt`, recording receiver-valued returns.

    Returns:
        `{receiver: {member: returned_receiver}}`, sorted.
    """
    from tools.parity.batcher_targets import receivers

    import batcher as bt

    table = receivers()
    by_class = {v: k for k, v in table.items() if inspect.isclass(v) and k not in ("bt",)}
    out: dict[str, dict[str, str]] = {}

    def record(receiver: str, name: str, fn: Any) -> None:
        target = _receiver_of(_annotation_class(fn), by_class)
        if target is not None:
            out.setdefault(receiver, {})[name] = target

    for receiver, cls in table.items():
        if not inspect.isclass(cls):
            continue
        for name, member in vars(cls).items():
            if name.startswith("_") and name != "__call__":
                continue
            fn = (
                member.fget if isinstance(member, property) else getattr(member, "__func__", member)
            )
            if inspect.isfunction(fn):
                record(receiver, name, fn)
    # Accessor properties are typed loosely in places; the receiver table is authoritative.
    for key in table:
        head, _, attr = key.rpartition(".")
        if head in table and inspect.isclass(table[head]):
            out.setdefault(head, {})[attr] = key
    for name in bt.__all__:
        obj = getattr(bt, name, None)
        if inspect.isfunction(obj):
            record("bt", name, obj)
        elif inspect.isclass(obj) and obj in by_class:
            out.setdefault("bt", {})[name] = by_class[obj]
    out.setdefault("bt", {})["read"] = "bt.read"
    return {r: dict(sorted(m.items())) for r, m in sorted(out.items())}


def render(data: dict[str, dict[str, str]]) -> str:
    """Serialize the table as TOML with a generated-file header.

    Args:
        data: The output of `generate`.

    Returns:
        The file contents.
    """
    lines = [_HEADER]
    for receiver, members in data.items():
        lines.append(f'\n["{receiver}"]')
        for name, target in members.items():
            lines.append(f'"{name}" = "{target}"')
    return "\n".join(lines) + "\n"


def main() -> int:
    """Write `returns.toml` and print a count."""
    import warnings

    warnings.filterwarnings("ignore")
    data = generate()
    OUT.write_text(render(data))
    print(f"{sum(len(v) for v in data.values())} returns over {len(data)} receivers -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
