"""Generate the receiver and signature tables the foreign-engine codemod directions follow.

`python -m batcher.migrate --from polars --to batcher` must know that `pl.scan_parquet(...)`
is a `LazyFrame`, that `.group_by(...)` on it is a `LazyGroupBy`, and that `pl.col("x").str`
is the string namespace, before it can look a method up in the migration registry. It must
also know which arguments a call may carry across: a keyword the target signature does not
accept is a rewrite the codemod refuses rather than guesses. The codemod imports none of the
four libraries (nor the engine), so both facts are generated here from the installed
libraries' own annotations and signatures and committed beside the registry as
`data/codemod/<engine>.toml`, plus `data/codemod/batcher.toml` for Batcher's side.

Each engine file holds two tables:

* `returns.<Surface>`: member -> the surface its call (or property) returns, for members whose
  annotation names exactly one surface class (or a subclass of one). Anything else ends the
  chain, which is what the codemod should do there too.
* `params.<Surface>`: member -> its parameters as tokens: `name`, `name=` (has a default),
  `*name`, `**name`, a bare `*` before keyword-only parameters, a bare `/` after
  positional-only ones, and `@property` for a property. A trailing `~` on a name marks a
  parameter whose annotation says a string there is a *column name* (PySpark `ColumnOrName`,
  Polars `IntoExpr`), which the codemod turns into `bt.col(...)`.

`tests/migrate/test_codemod_tables_fresh.py` regenerates each file in memory and fails on
drift, skipping an engine that is not installed. Run:
`python tools/parity/gen_codemod_tables.py [engine ...]`.
"""

from __future__ import annotations

import importlib
import inspect
import re
import sys
import warnings
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.parity.surfaces import SURFACES, _names, _resolve  # noqa: E402

OUT_DIR = ROOT / "python" / "batcher" / "_internal" / "migration" / "data" / "codemod"

_HEADER = """\
# GENERATED by tools/parity/gen_codemod_tables.py. Do not edit.
#
# What each {what} member returns, and its parameters, for the batcher.migrate codemod.
# Parameter tokens: `name`, `name=` (default), `*args`, `**kwargs`, `*` (keyword-only
# follow), `/` (positional-only precede), `@property`; a trailing `~` marks a column-name
# parameter.
"""

# Receivers that are not registry surfaces but sit on the chain from an import to one: the
# Spark session builder, Polars' `when/then/otherwise` builder, and `import ray` reaching
# `ray.data`.
_EXTRA_CLASSES: dict[str, list[tuple[str, str]]] = {
    "pyspark": [
        ("SparkSession.class", "pyspark.sql:SparkSession"),
        ("SparkSession.Builder", "pyspark.sql:SparkSession.Builder"),
    ],
    "polars": [
        (name, f"polars.expr.whenthen:{name}")
        for name in ("When", "Then", "ChainedWhen", "ChainedThen")
    ],
}
_EXTRA_RETURNS: dict[str, dict[str, dict[str, str]]] = {
    "pyspark": {
        "SparkSession.class": {"builder": "SparkSession.Builder"},
        "SparkSession.Builder": {"getOrCreate": "SparkSession", "create": "SparkSession"},
    },
    # `Dataset.rename_columns` carries no return annotation; its docstring returns a Dataset.
    "ray_data": {
        "ray": {"data": "ray.data"},
        "ray.data": {"expressions": "expressions", "aggregate": "aggregate"},
        "Dataset": {"rename_columns": "Dataset"},
    },
    "daft": {"daft": {"functions": "functions"}},
}

_COLUMN_ANNOTATION = {
    "pyspark": re.compile(r"\bColumnOrName\b"),
    "polars": re.compile(r"\bIntoExpr(Column)?\b"),
}


def _labels(engine: str) -> dict[str, Any]:
    """Every surface label of an engine mapped to the object it names."""
    out: dict[str, Any] = {}
    for label, target, _kind in SURFACES[engine]:
        out[label] = _resolve(target)
    for label, target in _EXTRA_CLASSES.get(engine, []):
        module, _, rest = target.partition(":")
        obj = importlib.import_module(module)
        for attr in rest.split("."):
            obj = getattr(obj, attr)
        out[label] = obj
    return out


def _classes(labels: dict[str, Any]) -> dict[type, str]:
    found: dict[type, str] = {}
    for label, obj in labels.items():
        if inspect.isclass(obj) and not label.endswith(".class"):
            found.setdefault(obj, label)
    return found


def _annotation_text(fn: Any) -> str | None:
    try:
        raw = inspect.signature(fn).return_annotation
    except (TypeError, ValueError):
        return None
    if raw is inspect.Signature.empty:
        return None
    return raw.__name__ if inspect.isclass(raw) else str(raw)


def _returned(fn: Any, owner: str | None, classes: dict[type, str]) -> str | None:
    """The one surface label a function's return annotation names, if exactly one."""
    text = _annotation_text(fn)
    if text is None:
        return None
    names = {n.rpartition(".")[2] for n in re.findall(r"[A-Za-z_][A-Za-z0-9_.]*", text)}
    if "Self" in names and owner is not None:
        return owner
    by_name = {cls.__name__: label for cls, label in classes.items()}
    hits = {by_name[n] for n in names if n in by_name}
    if not hits:
        glob = getattr(inspect.unwrap(fn), "__globals__", {})
        for n in names:
            obj = glob.get(n)
            if inspect.isclass(obj):
                hits |= {label for cls, label in classes.items() if issubclass(obj, cls)}
    # `Expr.str` is itself a class label; prefer the most specific single answer.
    return next(iter(hits)) if len(hits) == 1 else None


def _params(fn: Any, engine: str) -> list[str] | None:
    try:
        sig = inspect.signature(fn)
    except (TypeError, ValueError):
        return None
    column = _COLUMN_ANNOTATION.get(engine)
    tokens: list[str] = []
    kw_marked = False
    params = list(sig.parameters.values())
    if params and params[0].name in ("self", "cls"):
        params = params[1:]
    for i, p in enumerate(params):
        name = p.name
        annotation = p.annotation
        text = annotation if isinstance(annotation, str) else str(annotation)
        if column is not None and column.search(text):
            name += "~"
        if p.kind is p.VAR_POSITIONAL:
            tokens.append(f"*{name}")
            kw_marked = True
        elif p.kind is p.VAR_KEYWORD:
            tokens.append(f"**{name}")
        else:
            if p.kind is p.KEYWORD_ONLY and not kw_marked:
                tokens.append("*")
                kw_marked = True
            tokens.append(name + ("=" if p.default is not p.empty else ""))
            nxt = params[i + 1] if i + 1 < len(params) else None
            if p.kind is p.POSITIONAL_ONLY and (nxt is None or nxt.kind is not p.POSITIONAL_ONLY):
                tokens.append("/")
    return tokens


def _unwrap(member: Any) -> Any:
    """The function behind a static/class method; a plain `getattr(m, "__func__")` is wrong
    here because a Polars `Col` answers every attribute with an expression."""
    if isinstance(member, (staticmethod, classmethod)) or inspect.ismethod(member):
        return member.__func__
    return member


def _members(obj: Any, label: str, engine: str) -> dict[str, Any]:
    kinds = {lab: kind for lab, _t, kind in SURFACES.get(engine, [])}
    if inspect.isclass(obj):
        found: dict[str, Any] = {}
        for klass in reversed(obj.__mro__):
            if klass is object:
                continue
            for name, member in vars(klass).items():
                if not name.startswith("_") or name == "__call__":
                    found[name] = member
        return found
    names = _names(obj, kinds.get(label, "public"))
    return {n: getattr(obj, n, None) for n in names}


def generate_engine(engine: str) -> dict[str, dict[str, dict[str, Any]]]:
    """Walk one installed engine's surfaces.

    Args:
        engine: One of the migration registry's engines.

    Returns:
        `{"returns": {surface: {member: surface}}, "params": {surface: {member: tokens}}}`.
    """
    labels = _labels(engine)
    classes = _classes(labels)
    returns: dict[str, dict[str, str]] = {}
    params: dict[str, dict[str, list[str]]] = {}
    for label, obj in labels.items():
        owner = None if label.endswith(".class") or not inspect.isclass(obj) else label
        for name, member in _members(obj, label, engine).items():
            if isinstance(member, property):
                params.setdefault(label, {})[name] = ["@property"]
                target = _returned(member.fget, owner, classes) if member.fget else None
            elif inspect.isclass(member):
                target = classes.get(member)
                sig = _params(member, engine)
                if sig is not None:
                    params.setdefault(label, {})[name] = sig
            else:
                fn = _unwrap(member)
                if not callable(fn):
                    continue
                if not (inspect.isfunction(fn) or inspect.ismethod(fn) or inspect.isbuiltin(fn)):
                    # A callable instance (`pl.col` is a `Col`): its class's `__call__` holds
                    # the signature, and `inspect.signature` on the instance can fail.
                    fn = type(fn).__call__
                target = _returned(fn, owner, classes)
                sig = _params(fn, engine)
                if sig is not None:
                    params.setdefault(label, {})[name] = sig
            if target is not None:
                returns.setdefault(label, {})[name] = target
    for label, extra in _EXTRA_RETURNS.get(engine, {}).items():
        returns.setdefault(label, {}).update(extra)
    return {"returns": _sorted(returns), "params": _sorted(params)}


def generate_batcher() -> dict[str, dict[str, dict[str, Any]]]:
    """Walk Batcher's receivers for the parameters every registry target accepts.

    Returns:
        `{"params": {receiver: {member: tokens}}}`; the returns live in `returns.toml`.
    """
    from tools.parity.batcher_targets import receivers

    params: dict[str, dict[str, list[str]]] = {}
    for receiver, obj in receivers().items():
        if not (inspect.isclass(obj) or receiver == "bt"):
            continue
        members = (
            {n: getattr(obj, n, None) for n in obj.__all__}
            if receiver == "bt"
            else {
                n: m
                for klass in reversed(obj.__mro__)
                if klass is not object
                for n, m in vars(klass).items()
                if not n.startswith("_") or n == "__call__"
            }
        )
        for name, member in members.items():
            if isinstance(member, property):
                params.setdefault(receiver, {})[name] = ["@property"]
                continue
            fn = _unwrap(member)
            if callable(fn) and (sig := _params(fn, "batcher")) is not None:
                params.setdefault(receiver, {})[name] = sig
    return {"params": _sorted(params)}


def _sorted(table: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {k: dict(sorted(v.items())) for k, v in sorted(table.items())}


def _quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(data: dict[str, dict[str, dict[str, Any]]], what: str) -> str:
    """Serialize one engine's tables as TOML with a generated-file header.

    Args:
        data: The output of `generate_engine` or `generate_batcher`.
        what: The engine name, for the header.

    Returns:
        The file contents.
    """
    lines = [_HEADER.format(what=what)]
    for table, surfaces in data.items():
        for surface, members in surfaces.items():
            lines.append(f"\n[{table}.{_quote(surface)}]")
            for name, value in members.items():
                rendered = (
                    _quote(value)
                    if isinstance(value, str)
                    else "[" + ", ".join(_quote(v) for v in value) + "]"
                )
                lines.append(f"{_quote(name)} = {rendered}")
    return "\n".join(lines) + "\n"


def installed(engine: str) -> bool:
    """Whether an engine's distribution is importable here.

    Args:
        engine: A registry engine, or `batcher`.

    Returns:
        True when its tables can be generated on this machine.
    """
    import importlib.util

    module = {"ray_data": "ray.data", "batcher": "batcher"}.get(engine, engine)
    try:
        return importlib.util.find_spec(module) is not None
    except ModuleNotFoundError:
        return False


def main(argv: list[str]) -> int:
    """Write the tables for each requested (default: every installed) engine."""
    warnings.filterwarnings("ignore")
    engines = argv or [*SURFACES, "batcher"]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for engine in engines:
        if not installed(engine):
            print(f"{engine}: not installed, table left as is", file=sys.stderr)
            continue
        data = generate_batcher() if engine == "batcher" else generate_engine(engine)
        path = OUT_DIR / f"{engine}.toml"
        path.write_text(render(data, engine))
        counts = {t: sum(len(m) for m in s.values()) for t, s in data.items()}
        print(f"{engine}: {counts} -> {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
